/* -*- Mode: c++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4; c-file-style: "stroustrup" -*-
 *
 * Copyright (C) 1995-2011 Opera Software AS.  All rights reserved.
 *
 * This file is part of the Opera web browser.
 * It may not be distributed under any circumstances.
 */

/**
 *                    This file is auto generated
 *
 *                    !!! DO NOT EDIT BY HAND !!!
 *
 * Edit errors.txt and run mkerrors.py, both in modules/logdoc/scripts.
 */

enum ErrorCode
{
	GENERIC
	, CONT_BEFORE_DOCTYPE
	, MALPLACED_DOCTYPE
	, ILLEGAL_ENDTAG
	, ILLEGAL_STARTTAG
	, ILLEGAL_CONTENT
	, ILLEGAL_CONTENT_CLOSING
	, ILLEGAL_CONTENT_FOSTER
	, STRAY_ELEMENT
	, ILLEGAL_FRAMESET
	, ILLEGAL_NESTING
	, ILLEGAL_UNCLOSED
	, DEPRECATED
	, MALPLACED_TABLE_CONTENT
	, UNEXPECTED_EOF
	, UNEXPECTED_CHARACTER
	, EXPECTED_GREATER_THAN
	, EXPECTED_END_QUOTE
	, EXPECTED_TAG_NAME
	, EXPECTED_COMMENT_CONTENT
	, GOT_GRAVE_ACCENT_WHERE_APOSTROPHE_EXPECTED
	, INVALID_MARKUP_DECLARATION
	, BOGUS_DOCTYPE
	, DOCTYPE_EXPECTED_SPACE_BEFORE_NAME
	, DOCTYPE_EXPECTED_NAME
	, DOCTYPE_EXPECTED_SPACE_BEFORE_PUBLIC_IDENTIFIER
	, DOCTYPE_EXPECTED_PUBLIC_IDENTIFIER
	, DOCTYPE_EXPECTED_SPACE_BEFORE_SYSTEM_IDENTIFIER
	, DOCTYPE_EXPECTED_SYSTEM_IDENTIFIER
	, EXPECTED_ATTRIBUTE_VALUE
	, ATTRIBUTE_IN_END_TAG
	, SELF_CLOSING_END_TAG
	, ILLEGAL_SELF_CLOSING
	, DUPLICATE_ATTRIBUTE
	, INVALID_NUMERIC_ENTITY
	, INVALID_CHARACTER
	, INVALID_NAMED_ENTITY
	, EXPECTED_SEMICOLON_AT_END_OF_ENTITY
};
