// Vertex shader: cpp-macro-05.vs
float julia_dist(vec4 x);
vec3 julia_grad(vec4 z)
{
    vec3 grad;
    grad.x = julia_dist(z + vec4(1e4, 0.0, 0.0, 0.0)) - julia_dist(z - vec4(1e4, 0.0, 0.0, 1e4));
    grad.y = julia_dist(z + vec4(0.0, 1e4, 0.0, 0.0)) - julia_dist(z - vec4(0.0, 1e4, 0.0, 0.0));
    grad.z = julia_dist(z + vec4(0.0, 0.0, 1e4, 0.0)) - julia_dist(z - vec4(0.0, 0.0, 1e4, 0.0));
    return (grad);
}
void main()
{

}
