// Vertex shader: cpp-macro-06.vs
attribute vec4 aPosition;
varying vec4 vColor;
void main()
{
    gl_Position = aPosition;
    vec2 texcoord = vec2(aPosition.xy * 0.5 + vec2(0.5, 0.5));
    vec4 color = vec4(texcoord, texcoord.x * texcoord.y, (1.0 - texcoord.x) * texcoord.y * 0.5 + 0.5);
    vColor = vec4((color.x * 2.0 - 1.0 == 0.0 ? 0.0 : color.x * 2.0 - 1.0 > 0.0 ? 1.0 : -1.0) * 0.5 + 0.5, (color.y * 2.0 - 1.0 == 0.0 ? 0.0 : color.y * 2.0 - 1.0 > 0.0 ? 1.0 : -1.0) * 0.5 + 0.5, 0, 1);
}
