cbuffer webgl_cbuffer : register (b0)
{

};

struct webgl_ps_out_struct
{

};

struct webgl_vs_out_struct
{
    float4 gl_Position: SV_Position0;

};
static webgl_vs_out_struct webgl_in;
float f(float3 v)
{
    return (float(v.x));
}
webgl_ps_out_struct webgl_fs(webgl_vs_out_struct webgl_in)
{
    ::webgl_in = webgl_in;
    webgl_ps_out_struct webgl_out;
    f(float3(1, 1, 1));
    return;
    return webgl_out;
}
