/*
 *  custombuild-features.h
 *  Opera
 *
 *  Created by Adam Minchinton on 9/17/07.
 *  Copyright 2007 Opera Software ASA. All rights reserved.
 *
 *  This file is AUTOGENERATED, DO NOT add anything to it
 *
 */


