/* -*- Mode: c++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*-
**
** Copyright (C) 1995-2010 Opera Software AS.  All rights reserved.
**
** This file is part of the Opera web browser.  It may not be distributed
** under any circumstances.
*/

#ifndef QUICK_ACTIONS_H
#define QUICK_ACTIONS_H

#define ACTION_DEBUG_ENABLED                                        	YES
#define ACTION_GO_ENABLED                                           	YES
#define ACTION_CLOSE_CYCLER_ENABLED                                 	YES
#define ACTION_FOCUS_NEXT_WIDGET_ENABLED                            	YES
#define ACTION_FOCUS_PREVIOUS_WIDGET_ENABLED                        	YES
#define ACTION_CLICK_DEFAULT_BUTTON_ENABLED                         	YES
#define ACTION_CLICK_BUTTON_ENABLED                                 	YES
#define ACTION_SELECT_ALL_ENABLED                                   	YES
#define ACTION_DESELECT_ALL_ENABLED                                 	YES
#define ACTION_UNDO_ENABLED                                         	YES
#define ACTION_REDO_ENABLED                                         	YES
#define ACTION_CLEAR_ENABLED                                        	YES
#define ACTION_INSERT_ENABLED                                       	YES
#define ACTION_TOGGLE_OVERSTRIKE_ENABLED                            	YES
#define ACTION_CONVERT_HEX_TO_UNICODE_ENABLED                       	YES
#define ACTION_DELETE_ENABLED                                       	YES
#define ACTION_DELETE_WORD_ENABLED                                  	YES
#define ACTION_DELETE_TO_END_OF_LINE_ENABLED                        	YES
#define ACTION_BACKSPACE_ENABLED                                    	YES
#define ACTION_BACKSPACE_WORD_ENABLED                               	YES
#define ACTION_BACK_ENABLED                                         	YES
#define ACTION_FORWARD_ENABLED                                      	YES
#define ACTION_HIGHLIGHT_NEXT_URL_ENABLED                           	YES
#define ACTION_HIGHLIGHT_PREVIOUS_URL_ENABLED                       	YES
#define ACTION_HIGHLIGHT_NEXT_HEADING_ENABLED                       	YES
#define ACTION_HIGHLIGHT_PREVIOUS_HEADING_ENABLED                   	YES
#define ACTION_HIGHLIGHT_NEXT_ELEMENT_ENABLED                       	YES
#define ACTION_HIGHLIGHT_PREVIOUS_ELEMENT_ENABLED                   	YES
#define ACTION_HIGHLIGHT_NEXT_BLOCK_ENABLED                         	YES
#define ACTION_HIGHLIGHT_PREVIOUS_BLOCK_ENABLED                     	YES
#define ACTION_HIGHLIGHT_CURRENT_BLOCK_ENABLED                      	YES
#define ACTION_FOCUS_NEXT_FRAME_ENABLED                             	YES
#define ACTION_FOCUS_PREVIOUS_FRAME_ENABLED                         	YES
#define ACTION_SEARCH_ENABLED                                       	YES
#define ACTION_OPEN_LINK_ENABLED                                    	YES
#define ACTION_OPEN_LINK_IN_NEW_PAGE_ENABLED                        	YES
#define ACTION_OPEN_LINK_IN_NEW_WINDOW_ENABLED                      	YES
#define ACTION_OPEN_LINK_IN_BACKGROUND_PAGE_ENABLED                 	YES
#define ACTION_OPEN_LINK_IN_BACKGROUND_WINDOW_ENABLED               	YES
#define ACTION_ZOOM_TO_ENABLED                                      	YES
#define ACTION_ZOOM_IN_ENABLED                                      	YES
#define ACTION_ZOOM_OUT_ENABLED                                     	YES
#define ACTION_ZOOM_POINT_ENABLED                                   	YES
#define ACTION_SCROLL_ENABLED                                       	YES
#define ACTION_SCROLL_LEFT_ENABLED                                  	YES
#define ACTION_SCROLL_RIGHT_ENABLED                                 	YES
#define ACTION_SCROLL_UP_ENABLED                                    	YES
#define ACTION_SCROLL_DOWN_ENABLED                                  	YES
#define ACTION_GO_TO_START_ENABLED                                  	YES
#define ACTION_GO_TO_END_ENABLED                                    	YES
#define ACTION_GO_TO_CONTENT_MAGIC_ENABLED                          	YES
#define ACTION_GO_TO_NEXT_TAG_ENABLED                               	YES
#define ACTION_GO_TO_TOP_CM_BOTTOM_ENABLED                          	YES
#define ACTION_GO_TO_LINE_START_ENABLED                             	YES
#define ACTION_GO_TO_LINE_END_ENABLED                               	YES
#define ACTION_PAGE_UP_ENABLED                                      	YES
#define ACTION_PAGE_DOWN_ENABLED                                    	YES
#define ACTION_PAGE_LEFT_ENABLED                                    	YES
#define ACTION_PAGE_RIGHT_ENABLED                                   	YES
#define ACTION_NEXT_ITEM_ENABLED                                    	YES
#define ACTION_PREVIOUS_ITEM_ENABLED                                	YES
#define ACTION_NEXT_CHARACTER_ENABLED                               	YES
#define ACTION_PREVIOUS_CHARACTER_ENABLED                           	YES
#define ACTION_NEXT_WORD_ENABLED                                    	YES
#define ACTION_PREVIOUS_WORD_ENABLED                                	YES
#define ACTION_NEXT_LINE_ENABLED                                    	YES
#define ACTION_PREVIOUS_LINE_ENABLED                                	YES
#define ACTION_RANGE_GO_TO_START_ENABLED                            	YES
#define ACTION_RANGE_GO_TO_END_ENABLED                              	YES
#define ACTION_RANGE_GO_TO_LINE_START_ENABLED                       	YES
#define ACTION_RANGE_GO_TO_LINE_END_ENABLED                         	YES
#define ACTION_RANGE_PAGE_UP_ENABLED                                	YES
#define ACTION_RANGE_PAGE_DOWN_ENABLED                              	YES
#define ACTION_RANGE_PAGE_LEFT_ENABLED                              	YES
#define ACTION_RANGE_PAGE_RIGHT_ENABLED                             	YES
#define ACTION_RANGE_NEXT_ITEM_ENABLED                              	YES
#define ACTION_RANGE_PREVIOUS_ITEM_ENABLED                          	YES
#define ACTION_RANGE_NEXT_CHARACTER_ENABLED                         	YES
#define ACTION_RANGE_PREVIOUS_CHARACTER_ENABLED                     	YES
#define ACTION_RANGE_NEXT_WORD_ENABLED                              	YES
#define ACTION_RANGE_PREVIOUS_WORD_ENABLED                          	YES
#define ACTION_RANGE_NEXT_LINE_ENABLED                              	YES
#define ACTION_RANGE_PREVIOUS_LINE_ENABLED                          	YES
#define ACTION_CHECK_ITEM_ENABLED                                   	YES
#define ACTION_UNCHECK_ITEM_ENABLED                                 	YES
#define ACTION_SHOW_DROPDOWN_ENABLED                                	YES
#define ACTION_CLOSE_DROPDOWN_ENABLED                               	YES
#define ACTION_LEFT_ADJUST_TEXT_ENABLED                             	YES
#define ACTION_RIGHT_ADJUST_TEXT_ENABLED                            	YES
#define ACTION_DOWNLOAD_URL_ENABLED                                 	YES
#define ACTION_FORCE_RELOAD_ENABLED                                 	YES
#define ACTION_RELOAD_ENABLED                                       	YES
#define ACTION_STOP_ENABLED                                         	YES
#define ACTION_ACTIVATE_ELEMENT_ENABLED                             	YES
#define ACTION_FOCUS_NEXT_RADIO_WIDGET_ENABLED                      	YES
#define ACTION_FOCUS_PREVIOUS_RADIO_WIDGET_ENABLED                  	YES
#define ACTION_NAVIGATE_RIGHT_ENABLED                               	YES
#define ACTION_NAVIGATE_LEFT_ENABLED                                	YES
#define ACTION_NAVIGATE_UP_ENABLED                                  	YES
#define ACTION_NAVIGATE_DOWN_ENABLED                                	YES
#define ACTION_FOCUS_FORM_ENABLED                                   	YES
#define ACTION_UNFOCUS_FORM_ENABLED                                 	YES
#define ACTION_NAVIGATE_PAGE_UP_ENABLED                             	YES
#define ACTION_NAVIGATE_PAGE_DOWN_ENABLED                           	YES
#define ACTION_NAVIGATE_LEAVE_RIGHT_ENABLED                         	YES
#define ACTION_NAVIGATE_LEAVE_LEFT_ENABLED                          	YES
#define ACTION_NAVIGATE_LEAVE_UP_ENABLED                            	YES
#define ACTION_NAVIGATE_LEAVE_DOWN_ENABLED                          	YES
#define ACTION_SWITCH_TO_NEXT_PAGE_ENABLED                          	YES
#define ACTION_SWITCH_TO_PREVIOUS_PAGE_ENABLED                      	YES
#define ACTION_GO_TO_HOMEPAGE_ENABLED                               	YES
#define ACTION_WAND_ENABLED                                         	YES
#define ACTION_SHOW_HIDDEN_POPUP_MENU_ENABLED                           YES
#define ACTION_SHOW_POPUP_MENU_ENABLED                              	YES
#define ACTION_SHOW_POPUP_MENU_WITH_MENU_CONTEXT_ENABLED				YES
#define ACTION_HANDLE_DOC_CONTEXT_MENU_CLICK_ENABLED					YES
#define ACTION_SHOW_LINK_POPUP_MENU_ENABLED                         	YES
#define ACTION_SYNC_NOW_ENABLED                                        	YES
#define ACTION_EXTERNAL_ACTION_ENABLED                              	YES
#define ACTION_PASTE_MOUSE_SELECTION_ENABLED                        	YES
#define ACTION_CUT_ENABLED                                          	YES
#define ACTION_COPY_ENABLED                                         	YES
#define ACTION_COPY_TO_NOTE_ENABLED                                 	YES
#define ACTION_COPY_LABEL_TEXT_ENABLED                              	YES
#define ACTION_PASTE_ENABLED                                        	YES
#define ACTION_PASTE_TO_NOTE_ENABLED                                	YES
#define ACTION_PASTE_AND_GO_ENABLED                                 	YES
#define ACTION_TOGGLE_STYLE_BOLD_ENABLED                            	YES
#define ACTION_TOGGLE_STYLE_ITALIC_ENABLED                          	YES
#define ACTION_TOGGLE_STYLE_UNDERLINE_ENABLED                       	YES
#define ACTION_CHANGE_DIRECTION_TO_LTR_ENABLED                      	YES
#define ACTION_CHANGE_DIRECTION_TO_RTL_ENABLED                      	YES
#define ACTION_ENABLE_HANDHELD_MODE_ENABLED                         	YES
#define ACTION_DISABLE_HANDHELD_MODE_ENABLED                        	YES
#define ACTION_ENABLE_MSR_ENABLED                                   	YES
#define ACTION_DISABLE_MSR_ENABLED                                  	YES
#define ACTION_ENABLE_TVR_ENABLED                                   	YES
#define ACTION_DISABLE_TVR_ENABLED                                  	YES
#define ACTION_FIND_PREVIOUS_ENABLED                                	YES
#define ACTION_IM_STATUS_CHANGED_ENABLED                            	YES
#define ACTION_SPELL_CHECK_ENABLED                                  	YES
#define ACTION_SPELL_IGNORE_WORD_ENABLED                            	YES
#define ACTION_SPELL_REPLACE_WORD_ENABLED                           	YES
#define ACTION_SPELL_ADD_WORD_ENABLED                               	YES
#define ACTION_SPELL_DELETE_WORD_ENABLED                            	YES
#define ACTION_SPELL_ADD_LANGUAGE_ENABLED                           	YES
#define ACTION_SPELL_DELETE_LANGUAGE_ENABLED                        	YES
#define ACTION_MENU_ENABLED                                         	YES
#define ACTION_CANCEL_MENU_ENABLED                                  	YES
#define ACTION_UP_DIALOG_ENABLED                                    	YES
#define ACTION_DOWN_DIALOG_ENABLED                                  	YES
#define ACTION_CANCEL_URL_ENABLED                                   	YES
#define ACTION_OPEN_URL_ENABLED                                     	YES
#define ACTION_GO_TO_URL_ENABLED                                    	YES
#define ACTION_DIALOG_LEFT_ENABLED                                  	YES
#define ACTION_DIALOG_MIDDLE_ENABLED                                	YES
#define ACTION_DIALOG_RIGHT_ENABLED                                 	YES
#define ACTION_BOOKMARKS_ENABLED                                    	YES
#define ACTION_CACHE_LIST_ENABLED                                   	YES
#define ACTION_ONLINE_ENABLED                                       	YES
#define ACTION_WINDOWS_LIST_ENABLED                                 	YES
#define ACTION_FRAMES_LIST_ENABLED                                  	YES
#define ACTION_KYO_SCROLL_UP_ENABLED                                	YES
#define ACTION_KYO_SCROLL_DOWN_ENABLED                              	YES
#define ACTION_KYO_PAGE_UP_ENABLED                                  	YES
#define ACTION_KYO_PAGE_DOWN_ENABLED                                	YES
#define ACTION_TOGGLE_INPUT_MODE_ENABLED                            	YES
#define ACTION_OPEN_LINK_ADDRESS_ENABLED                            	YES
#define ACTION_TOGGLE_SSR_ENABLED                                   	YES
#define ACTION_FOCUS_PAGE_ENABLED                                   	YES
#define ACTION_CYCLE_TO_NEXT_WINDOW_ENABLED                         	YES
#define ACTION_NEW_PAGE_ENABLED                                     	YES
#define ACTION_NEW_PRIVATE_PAGE_ENABLED									YES
#define ACTION_CLOSE_PAGE_ENABLED                                   	YES
#define ACTION_CYCLE_TO_NEXT_PAGE_ENABLED                           	YES
#define ACTION_CYCLE_TO_PREVIOUS_PAGE_ENABLED                       	YES
#define ACTION_FIND_ENABLED                                         	YES
#define ACTION_OK_ENABLED                                           	YES
#define ACTION_USER_PROFILE_ENABLED                                 	YES
#define ACTION_SVG_ZOOM_IN_ENABLED                                  	YES
#define ACTION_SVG_ZOOM_OUT_ENABLED                                 	YES
#define ACTION_SVG_ZOOM_ENABLED                                     	YES
#define ACTION_SVG_START_ANIMATION_ENABLED                          	YES
#define ACTION_SVG_STOP_ANIMATION_ENABLED                           	YES
#define ACTION_SVG_PAUSE_ANIMATION_ENABLED                          	YES
#define ACTION_SVG_SET_QUALITY_ENABLED                              	YES
#define ACTION_SVG_RESET_PAN_ENABLED									YES
#define ACTION_FIND_INLINE_ENABLED                                  	YES
#define ACTION_FIND_NEXT_ENABLED                                    	YES
#define ACTION_ENABLE_SCROLL_BARS_ENABLED                           	YES
#define ACTION_DISABLE_SCROLL_BARS_ENABLED                          	YES
#define ACTION_OPEN_BT_PREFS_ENABLED                                	YES
#define ACTION_LOCK_PAGE_ENABLED                                    	YES
#define ACTION_UNLOCK_PAGE_ENABLED                                  	YES
#define ACTION_SEND_MESSAGE_TO_CONTACT_ENABLED                      	YES
#define ACTION_VIEW_MESSAGES_FROM_CONTACT_ENABLED                   	YES
#define ACTION_VIEW_MESSAGES_FROM_SELECTED_CONTACT_ENABLED          	YES
#define ACTION_GET_MAIL_ENABLED                                     	YES
#define ACTION_SEND_MAIL_ENABLED                                    	YES
#define ACTION_SEND_QUEUED_MAIL_ENABLED                             	YES
#define ACTION_STOP_SEND_MAIL_ENABLED                               	YES
#define ACTION_SEND_ADDRESS_IN_MAIL_ENABLED                         	YES
#define ACTION_SEND_DOCUMENT_ADDRESS_IN_MAIL_ENABLED                	YES
#define ACTION_SEND_FRAME_ADDRESS_IN_MAIL_ENABLED                   	YES
#define ACTION_COMPOSE_MAIL_ENABLED                                 	YES
#define ACTION_QUICK_REPLY_ENABLED                                  	YES
#define ACTION_REPLY_ENABLED                                        	YES
#define ACTION_REPLY_ALL_ENABLED                                    	YES
#define ACTION_FORWARD_MAIL_ENABLED                                 	YES
#define ACTION_REDIRECT_MAIL_ENABLED                                	YES
#define ACTION_RESEND_MAIL_ENABLED                                  	YES
#define ACTION_SAVE_DRAFT_ENABLED                                   	YES
#define ACTION_EDIT_DRAFT_ENABLED                                   	YES
#define ACTION_OPEN_IN_MESSAGE_VIEW_ENABLED                         	YES
#define ACTION_DELETE_MAIL_ENABLED                                  	YES
#define ACTION_DELETE_PERMANENTLY_ENABLED                           	YES
#define ACTION_REMOVE_FROM_VIEW_ENABLED                             	YES
#define ACTION_ADD_TO_VIEW_ENABLED                                  	YES
#define ACTION_CANCEL_NEWSMESSAGE_ENABLED                           	YES
#define ACTION_COPY_RAW_MAIL_ENABLED                                	YES
#define ACTION_COPY_MAIL_TO_FOLDER_ENABLED                          	YES
#define ACTION_MARK_ALL_AS_READ_ENABLED                             	YES
#define ACTION_EMPTY_TRASH_ENABLED                                  	YES
#define ACTION_EMPTY_PAGE_TRASH_ENABLED                             	YES
#define ACTION_EMPTY_SPAM_ENABLED                                   	YES
#define ACTION_MARK_AND_SELECT_NEXT_UNREAD_ENABLED                  	YES
#define ACTION_SELECT_NEXT_UNREAD_ENABLED                           	YES
#define ACTION_SELECT_PREVIOUS_UNREAD_ENABLED                       	YES
#define ACTION_MARK_AS_READ_ENABLED                                 	YES
#define ACTION_MARK_AS_UNREAD_ENABLED                               	YES
#define ACTION_MARK_AS_SPAM_ENABLED                                 	YES
#define ACTION_MARK_AS_NOT_SPAM_ENABLED                             	YES
#define ACTION_COMPOSE_TO_CONTACT_ENABLED                           	YES
#define ACTION_COMPOSE_CC_CONTACT_ENABLED                           	YES
#define ACTION_COMPOSE_BCC_CONTACT_ENABLED                          	YES
#define ACTION_ADD_CONTACT_ENABLED                                  	YES
#define ACTION_ADD_NICK_TO_CONTACT_ENABLED                          	YES
#define ACTION_ADD_ATTACHMENT_ENABLED                               	YES
#define ACTION_REMOVE_ATTACHMENT_ENABLED                            	YES
#define ACTION_SEARCH_MAIL_ENABLED                                  	YES
#define ACTION_START_SEARCH_ENABLED                                 	YES
#define ACTION_SHOW_MAIL_FILTERS_ENABLED                            	YES
#define ACTION_SHOW_IN_UNREAD_ENABLED                               	YES
#define ACTION_HIDE_FROM_UNREAD_ENABLED                             	YES
#define ACTION_NEW_FILTER_ENABLED                                   	YES
#define ACTION_REMOVE_FILTER_ENABLED                                	YES
#define ACTION_SET_CHAT_STATUS_ENABLED                              	YES
#define ACTION_NEW_CHAT_ROOM_ENABLED                                	YES
#define ACTION_JOIN_CHAT_ROOM_ENABLED                               	YES
#define ACTION_JOIN_PRIVATE_CHAT_ENABLED                            	YES
#define ACTION_SEND_FILE_ENABLED                                    	YES
#define ACTION_LIST_CHAT_ROOMS_ENABLED                              	YES
#define ACTION_REFRESH_CHATROOM_LIST_ENABLED                        	YES
#define ACTION_LEAVE_CHAT_ROOM_ENABLED                              	YES
#define ACTION_EDIT_CHAT_ROOM_ENABLED                               	YES
#define ACTION_CHAT_COMMAND_ENABLED                                 	YES
#define ACTION_CHANGE_NICKNAME_ENABLED                              	YES
#define ACTION_SEND_MESSAGE_ENABLED                                 	YES
#define ACTION_STOP_MAIL_ENABLED                                    	YES
#define ACTION_READ_MAIL_ENABLED                                    	YES
#define ACTION_SUBSCRIBE_TO_GROUPS_ENABLED                          	YES
#define ACTION_NEW_ACCOUNT_ENABLED                                  	YES
#define ACTION_EDIT_ACCOUNT_ENABLED                                 	YES
#define ACTION_DELETE_ACCOUNT_ENABLED                               	YES
#define ACTION_MANAGE_ACCOUNTS_ENABLED                              	YES
#define ACTION_SHOW_ACCOUNT_ENABLED                                 	YES
#define ACTION_EXPORT_MAIL_INDEX_ENABLED                            	YES
#define ACTION_EXPORT_MAIL_MESSAGES_ENABLED                         	YES
#define ACTION_IMPORT_MAIL_ENABLED                                  	YES
#define	ACTION_IMPORT_NEWSFEED_LIST_ENABLED								YES
#define ACTION_EXPORT_NEWSFEED_LIST_ENABLED								YES
#define ACTION_SEND_TEXT_IN_MAIL_ENABLED                            	YES
#define ACTION_SET_MAIL_VIEW_TYPE_ENABLED                           	YES
#define ACTION_SET_MAIL_VIEW_FLAG_ENABLED                           	YES
#define ACTION_SET_MAIL_VIEW_AGE_ENABLED                            	YES
#define ACTION_CLEAR_MAIL_VIEW_FLAG_ENABLED                         	YES
#define ACTION_SET_MAIL_DISPLAY_TYPE_ENABLED                        	YES
#define ACTION_SHOW_QUICK_REPLY_ENABLED                             	YES
#define ACTION_SHOW_SPLIT_VIEW_ENABLED                              	YES
#define ACTION_SHOW_MESSAGE_VIEW_ENABLED                            	YES
#define ACTION_SHOW_LIST_VIEW_ENABLED                               	YES
#define ACTION_MARK_AS_READ_AUTOMATICALLY_ENABLED                   	YES
#define ACTION_NEW_NEWSFEED_ENABLED                                 	YES
#define ACTION_READ_NEWSFEED_ENABLED                                	YES
#define ACTION_MARK_THREAD_AS_READ_ENABLED                          	YES
#define ACTION_MARK_THREAD_AND_SELECT_NEXT_UNREAD_ENABLED           	YES
#define ACTION_SUBSCRIBE_NEWSFEED_ENABLED                           	YES
#define ACTION_SHOW_RAW_MAIL_ENABLED                                	YES
#define ACTION_EXECUTE_PROGRAM_ENABLED                              	YES
#define ACTION_CANCEL_ENABLED                                       	YES
#define ACTION_NO_ENABLED                                           	YES
#define ACTION_OPEN_ENABLED                                         	YES
#define ACTION_SAVE_ENABLED                                         	YES
#define ACTION_CHANGE_ENABLED                                       	YES
#define ACTION_REMOVE_ENABLED                                       	YES
#define ACTION_REMOVE_PANEL_ENABLED                                 	YES
#define ACTION_EDIT_PANEL_ENABLED                                   	YES
#define ACTION_RESTORE_TO_DEFAULTS_ENABLED                          	YES
#define ACTION_UNDELETE_ENABLED                                     	YES
#define ACTION_REWIND_ENABLED                                       	YES
#define ACTION_FAST_FORWARD_ENABLED                                 	YES
#define ACTION_ENTER_ACCESS_KEY_MODE_ENABLED                        	YES
#define ACTION_LEAVE_ACCESS_KEY_MODE_ENABLED                        	YES
#define ACTION_LOAD_ALL_IMAGES_ENABLED                              	YES
#define ACTION_SELECT_AUTHOR_MODE_ENABLED                           	YES
#define ACTION_SELECT_USER_MODE_ENABLED                             	YES
#define ACTION_SELECT_USER_CSS_FILE_ENABLED                         	YES
#define ACTION_DESELECT_USER_CSS_FILE_ENABLED                       	YES
#define ACTION_SELECT_ALTERNATE_CSS_FILE_ENABLED                    	YES
#define ACTION_PRINT_PREVIEW_ENABLED                                	YES
#define ACTION_SHOW_PRINT_PREVIEW_AS_SCREEN_ENABLED                 	YES
#define ACTION_SHOW_PRINT_PREVIEW_ONE_FRAME_PER_SHEET_ENABLED       	YES
#define ACTION_SHOW_PRINT_PREVIEW_ACTIVE_FRAME_ENABLED              	YES
#define ACTION_LEAVE_PRINT_PREVIEW_ENABLED                          	YES
#define ACTION_ENTER_FULLSCREEN_ENABLED                             	YES
#define ACTION_LEAVE_FULLSCREEN_ENABLED                             	YES
#define ACTION_COPY_DOCUMENT_ADDRESS_ENABLED                        	YES
#define ACTION_COPY_LINK_ENABLED                                    	YES
#define ACTION_COPY_LINK_MAIL_ADDRESS_ENABLED                       	YES
#define ACTION_SAVE_LINK_ENABLED                                    	YES
#define ACTION_SAVE_IMAGE_ENABLED                                   	YES
#define ACTION_COPY_IMAGE_ADDRESS_ENABLED                           	YES
#define ACTION_SHOW_IMAGE_PROPERTIES_ENABLED                        	YES
#define ACTION_OPEN_IMAGE_ADDRESS_ENABLED                           	YES
#define ACTION_RELOAD_IMAGE_ENABLED                                 	YES
#define ACTION_OPEN_IMAGE_ENABLED                                   	YES
#define ACTION_LOAD_IMAGE_ENABLED                                   	YES
#define ACTION_LOAD_IMAGE_NON_TURBO_ENABLED                            	YES
#define ACTION_SHOW_BACKGROUND_IMAGE_ENABLED                        	YES
#define ACTION_SHOW_BACKGROUND_IMAGE_PROPERTIES_ENABLED             	YES
#define ACTION_COPY_BACKGROUND_IMAGE_ADDRESS_ENABLED                	YES
#define ACTION_SAVE_BACKGROUND_IMAGE_ENABLED                        	YES
#define ACTION_COPY_BACKGROUND_IMAGE_ENABLED                        	YES
#define ACTION_OPEN_BACKGROUND_IMAGE_ENABLED                        	YES
#define ACTION_USE_BACKGROUND_IMAGE_AS_FOREGROUND_SKIN_ENABLED      	YES
#define ACTION_USE_BACKGROUND_IMAGE_AS_BACKGROUND_SKIN_ENABLED      	YES
#define ACTION_USE_BACKGROUND_IMAGE_AS_DESKTOP_BACKGROUND_ENABLED   	YES
#define ACTION_USE_IMAGE_AS_DESKTOP_BACKGROUND_ENABLED              	YES
#define ACTION_COPY_IMAGE_ENABLED                                   	YES
#define ACTION_GO_TO_IMAGE_ENABLED                                  	YES
#define ACTION_USE_IMAGE_AS_FOREGROUND_SKIN_ENABLED                 	YES
#define ACTION_USE_IMAGE_AS_BACKGROUND_SKIN_ENABLED                 	YES
#define ACTION_REMOVE_FOREGROUND_SKIN_ENABLED                       	YES
#define ACTION_REMOVE_BACKGROUND_SKIN_ENABLED                       	YES
#define ACTION_MAXIMIZE_FRAME_ENABLED                               	YES
#define ACTION_OPEN_FRAME_IN_NEW_PAGE_ENABLED                       	YES
#define ACTION_OPEN_FRAME_IN_BACKGROUND_PAGE_ENABLED                	YES
#define ACTION_SAVE_FRAME_AS_ENABLED                                	YES
#define ACTION_SET_ENCODING_ENABLED                                 	YES
#define ACTION_HOTCLICK_SEARCH_ENABLED                              	YES
#define ACTION_EDIT_PROPERTIES_ENABLED                              	YES
#define ACTION_NEW_ITEM_ENABLED                                    	    YES
#define ACTION_DELETE_ITEM_ENABLED                                      YES
#define ACTION_EDIT_ITEM_ENABLED                                    	YES
#define ACTION_OPEN_ITEM_ENABLED                                    	YES
#define ACTION_OPEN_ALL_ITEMS_ENABLED                               	YES
#define ACTION_CLOSE_ITEM_ENABLED                                   	YES
#define ACTION_CLOSE_ALL_ITEMS_ENABLED                              	YES
#define ACTION_GO_TO_HISTORY_ENABLED                                	YES
#define ACTION_NEXT_TRACK_ENABLED                                   	YES
#define ACTION_PREVIOUS_TRACK_ENABLED                               	YES
#define ACTION_STOP_MUSIC_ENABLED                                   	YES
#define ACTION_PLAY_MUSIC_ENABLED                                   	YES
#define ACTION_PAUSE_MUSIC_ENABLED                                  	YES
#define ACTION_NEW_BROWSER_WINDOW_ENABLED                           	YES
#define ACTION_NEW_PRIVATE_BROWSER_WINDOW_ENABLED                       YES
#define ACTION_NEW_BOOKMARK_ENABLED                                 	YES
#define ACTION_NEW_CONTACT_ENABLED                                  	YES
#define ACTION_NEW_GROUP_ENABLED                                    	YES
#define ACTION_NEW_NOTE_ENABLED                                     	YES
#define ACTION_NEW_FOLDER_ENABLED                                   	YES
#define ACTION_NEW_SEPERATOR_ENABLED                                	YES
#define ACTION_NEW_SHORTCUT_ENABLED                                 	YES
#define ACTION_SHOW_NEW_PAGE_BUTTON_ENABLED                         	YES
#define ACTION_HIDE_NEW_PAGE_BUTTON_ENABLED                         	YES
#define ACTION_RESET_SHORTCUTS_ENABLED                              	YES
#define ACTION_ADD_MUSIC_ENABLED                                    	YES
#define ACTION_DETACH_PAGE_ENABLED                                  	YES
#define ACTION_CLOSE_WINDOW_ENABLED                                 	YES
#define ACTION_CLOSE_CLICKED_PAGE_ENABLED                           	YES
#define ACTION_REOPEN_PAGE_ENABLED                                  	YES
#define ACTION_OPEN_BLOCKED_POPUP_ENABLED                           	YES
#define ACTION_OPEN_DOCUMENT_ENABLED                                	YES
#define ACTION_SAVE_DOCUMENT_AS_ENABLED                             	YES
#define ACTION_SAVE_DOCUMENT_WITH_IMAGES_AS_ENABLED                 	YES
#define ACTION_SAVE_DOCUMENT_ENABLED                                	YES
#define ACTION_PRINT_DOCUMENT_ENABLED                               	YES
#define ACTION_SHOW_PRINT_SETUP_ENABLED                             	YES
#define ACTION_SHOW_PRINT_OPTIONS_ENABLED								YES
#define ACTION_LICENSE_VIEW_ENABLED										YES
#define ACTION_SYNC_SIGNUP_ENABLED										YES
#define ACTION_SYNC_OPTIONS_ENABLED										YES
#define ACTION_SYNC_LOGIN_ENABLED										YES
#define ACTION_SYNC_LOGOUT_ENABLED										YES
#define ACTION_SYNC_ACCEPT_ENABLED										YES
#define ACTION_SYNC_GUEST_ENABLED										YES
#define ACTION_SYNC_STANDARD_ENABLED									YES
#define ACTION_WORK_OFFLINE_ENABLED                                 	YES
#define ACTION_WORK_ONLINE_ENABLED                                  	YES
#define ACTION_DELETE_PRIVATE_DATA_ENABLED                          	YES
#define ACTION_SHOW_QUICK_PREFERENCES_ENABLED                       	YES
#define ACTION_SHOW_PREFERENCES_ENABLED                             	YES
#define ACTION_SHOW_FILE_HANDLERS_ENABLED                           	YES
#define ACTION_DELETE_SKIN_ENABLED                                  	YES
#define ACTION_RENAME_TOOLBAR_SETUP_ENABLED                         	YES
#define ACTION_DUPLICATE_TOOLBAR_SETUP_ENABLED                      	YES
#define ACTION_DELETE_TOOLBAR_SETUP_ENABLED                         	YES
#define ACTION_RENAME_MENU_SETUP_ENABLED                            	YES
#define ACTION_DUPLICATE_MENU_SETUP_ENABLED                         	YES
#define ACTION_DELETE_MENU_SETUP_ENABLED                            	YES
#define ACTION_RENAME_MOUSE_SETUP_ENABLED                           	YES
#define ACTION_DUPLICATE_MOUSE_SETUP_ENABLED                        	YES
#define ACTION_DELETE_MOUSE_SETUP_ENABLED                           	YES
#define ACTION_RENAME_KEYBOARD_SETUP_ENABLED                        	YES
#define ACTION_DUPLICATE_KEYBOARD_SETUP_ENABLED                     	YES
#define ACTION_DELETE_KEYBOARD_SETUP_ENABLED                        	YES
#define ACTION_EXIT_ENABLED                                         	YES
#define ACTION_ENABLE_INLINE_FIND_ENABLED                           	YES
#define ACTION_DISABLE_INLINE_FIND_ENABLED                          	YES
#define ACTION_SHOW_WEB_SEARCH_ENABLED                              	YES
#define ACTION_ENABLE_MENU_BAR_ENABLED                              	YES
#define ACTION_DISABLE_MENU_BAR_ENABLED                             	YES
#define ACTION_REFRESH_DISPLAY_ENABLED                              	YES
#define ACTION_VIEW_DOCUMENT_SOURCE_ENABLED                         	YES
#define ACTION_VIEW_FRAME_SOURCE_ENABLED                            	YES
#define ACTION_COPY_FRAME_ADDRESS_ENABLED                           	YES
#define ACTION_RELOAD_FRAME_ENABLED                                 	YES
#define ACTION_RELOAD_ALL_PAGES_ENABLED                             	YES
#define ACTION_RELOAD_PANEL_ENABLED                                 	YES
#define ACTION_SET_HOMEPAGE_ENABLED                                 	YES
#define ACTION_GO_TO_PAGE_ENABLED                                   	YES
#define ACTION_GO_TO_SIMILAR_PAGE_ENABLED                           	YES
#define ACTION_GO_TO_NICKNAME_ENABLED                               	YES
#define ACTION_GO_TO_LINK_ELEMENT_ENABLED                           	YES
#define ACTION_ADD_TO_BOOKMARKS_ENABLED                             	YES
#define ACTION_ADD_FRAME_TO_BOOKMARKS_ENABLED                       	YES
#define ACTION_ADD_ALL_TO_BOOKMARKS_ENABLED                         	YES
#define ACTION_ADD_TRUSTED_APPLICATION_ENABLED                      	YES
#define ACTION_MANAGE_ENABLED                                       	YES
#define ACTION_MANAGE_TRUSTED_APPLICATION_ENABLED                   	YES
#define ACTION_MANAGE_BOOKMARKS_ENABLED                             	YES
#define ACTION_MANAGE_MOUSE_ENABLED                                 	YES
#define ACTION_MANAGE_KEYBOARD_ENABLED                              	YES
#define ACTION_MANAGE_WAND_ENABLED                                  	YES
#define ACTION_MANAGE_COOKIES_ENABLED                               	YES
#define ACTION_MANAGE_LINKS_ENABLED                                 	YES
#define ACTION_MANAGE_CERTIFICATES_ENABLED                          	YES
#define ACTION_MANAGE_MODES_ENABLED                                 	YES
#define ACTION_MANAGE_SCRIPT_OPTIONS_ENABLED                        	YES
#define ACTION_MANAGE_MIDDLE_CLICK_OPTIONS_ENABLED                  	YES
#define ACTION_MANAGE_PLUGINS_ENABLED                               	YES
#define ACTION_MANAGE_JAVA_ENABLED                                  	YES
#define ACTION_CHANGE_MASTERPASSWORD_ENABLED                        	YES
#define ACTION_SORT_BY_COLUMN_ENABLED                               	YES
#define ACTION_SORT_DIRECTION_ENABLED                               	YES
#define ACTION_SHOW_COLUMN_ENABLED                                  	YES
#define ACTION_HIDE_COLUMN_ENABLED                                  	YES
#define ACTION_DUPLICATE_PAGE_ENABLED                               	YES
#define ACTION_CREATE_LINKED_WINDOW_ENABLED                         	YES
#define ACTION_CASCADE_ENABLED                                      	YES
#define ACTION_TILE_VERTICALLY_ENABLED                              	YES
#define ACTION_TILE_HORIZONTALLY_ENABLED                            	YES
#define ACTION_RESTORE_PAGE_ENABLED                                 	YES
#define ACTION_MINIMIZE_PAGE_ENABLED                                	YES
#define ACTION_MAXIMIZE_PAGE_ENABLED                                	YES
#define ACTION_RESTORE_WINDOW_ENABLED                               	YES
#define ACTION_MINIMIZE_WINDOW_ENABLED                              	YES
#define ACTION_MAXIMIZE_WINDOW_ENABLED                              	YES
#define ACTION_RESTORE_ALL_ENABLED                                  	YES
#define ACTION_MINIMIZE_ALL_ENABLED                                 	YES
#define ACTION_MAXIMIZE_ALL_ENABLED                                 	YES
#define ACTION_CLOSE_ALL_ENABLED                                    	YES
#define ACTION_CLOSE_OTHER_ENABLED                                  	YES
#define ACTION_SAVE_WINDOW_SETUP_ENABLED                            	YES
#define ACTION_SHOW_SEARCH_ENABLED                                  	YES
#define ACTION_HIDE_SEARCH_ENABLED                                  	YES
#define ACTION_SELECT_SKIN_ENABLED                                  	YES
#define ACTION_SELECT_SESSION_ENABLED                               	YES
#define ACTION_OPEN_SESSION_ENABLED                                 	YES
#define ACTION_INSERT_SESSION_ENABLED                               	YES
#define ACTION_SHOW_WINDOW_LIST_ENABLED                             	YES
#define ACTION_SHOW_HELP_ENABLED                                    	YES
#define ACTION_CHECK_FOR_UPDATE_ENABLED                             	YES
#define ACTION_SHOW_SECURITY_INFORMATION_ENABLED                    	YES
#define ACTION_SHOW_SECURITY_PAGE_ENABLED                    	        YES
#define ACTION_SHOW_PERMISSIONS_PAGE_ENABLED               	            YES
#define ACTION_OPEN_BOOKMARKS_FILE_ENABLED                          	YES
#define ACTION_SAVE_SELECTED_BOOKMARKS_AS_ENABLED                   	YES
#define ACTION_EXPORT_BOOKMARKS_ENABLED                             	YES
#define ACTION_EXPORT_BOOKMARKS_TO_HTML_ENABLED                     	YES
#define ACTION_EXPORT_SELECTED_BOOKMARKS_TO_HTML_ENABLED            	YES
#define ACTION_NEW_CONTACTS_FILE_ENABLED                            	YES
#define ACTION_OPEN_CONTACTS_FILE_ENABLED                           	YES
#define ACTION_INSERT_CONTACTS_FILE_ENABLED                         	YES
#define ACTION_SAVE_CONTACTS_ENABLED                                	YES
#define ACTION_SAVE_SELECTED_CONTACTS_AS_ENABLED                    	YES
#define ACTION_EXPORT_CONTACTS_ENABLED                              	YES
#define ACTION_IMPORT_BOOKMARKS_ENABLED                             	YES
#define ACTION_IMPORT_CONTACTS_ENABLED                              	YES
#define ACTION_IMPORT_NETSCAPE_BOOKMARKS_ENABLED                    	YES
#define ACTION_IMPORT_EXPLORER_FAVORITES_ENABLED                    	YES
#define ACTION_IMPORT_KDE1_BOOKMARKS_ENABLED                        	YES
#define ACTION_IMPORT_KONQUEROR_BOOKMARKS_ENABLED                   	YES
#define ACTION_ENABLE_POPUP_WINDOWS_ENABLED                         	YES
#define ACTION_DISABLE_POPUP_WINDOWS_ENABLED                        	YES
#define ACTION_ENABLE_POPUP_WINDOWS_IN_BACKGROUND_ENABLED           	YES
#define ACTION_ENABLE_REQUESTED_POPUP_WINDOWS_ENABLED               	YES
#define ACTION_ENABLE_GIF_ANIMATION_ENABLED                         	YES
#define ACTION_DISABLE_GIF_ANIMATION_ENABLED                        	YES
#define ACTION_ENABLE_JAVA_ENABLED                                  	YES
#define ACTION_DISABLE_JAVA_ENABLED                                 	YES
#define ACTION_ENABLE_JAVASCRIPT_ENABLED                            	YES
#define ACTION_DISABLE_JAVASCRIPT_ENABLED                           	YES
#define ACTION_ENABLE_PLUGINS_ENABLED                               	YES
#define ACTION_DISABLE_PLUGINS_ENABLED                              	YES
#define ACTION_ENABLE_COOKIES_ENABLED                               	YES
#define ACTION_DISABLE_COOKIES_ENABLED                              	YES
#define ACTION_ENABLE_REFERRER_LOGGING_ENABLED                      	YES
#define ACTION_DISABLE_REFERRER_LOGGING_ENABLED                     	YES
#define ACTION_ENABLE_PROXY_SERVERS_ENABLED                         	YES
#define ACTION_DISABLE_PROXY_SERVERS_ENABLED                        	YES
#define ACTION_IDENTIFY_AS_ENABLED                                  	YES
#define ACTION_ENABLE_AUTOMATIC_RELOAD_ENABLED                      	YES
#define ACTION_DISABLE_AUTOMATIC_RELOAD_ENABLED                     	YES
#define ACTION_SET_AUTOMATIC_RELOAD_ENABLED                         	YES
#define ACTION_SHOW_TRANSFERS_ENABLED                               	YES
#define ACTION_SHOW_JAVA_CONSOLE_ENABLED                            	YES
#define ACTION_ADD_PANEL_ENABLED                                    	YES
#define ACTION_GO_TO_CONTACT_HOMEPAGE_ENABLED                       	YES
#define ACTION_SHOW_ON_PERSONAL_BAR_ENABLED                         	YES
#define ACTION_HIDE_FROM_PERSONAL_BAR_ENABLED                       	YES
#define ACTION_VIEW_HOTLIST_ENABLED                                 	YES
#define ACTION_VIEW_STYLE_ENABLED                                   	YES
#define ACTION_HOTLIST_ALWAYS_ON_TOP_ENABLED                        	YES
#define ACTION_SET_SKIN_COLORING_ENABLED                            	YES
#define ACTION_USE_SYSTEM_SKIN_COLORING_ENABLED                     	YES
#define ACTION_DISABLE_SKIN_COLORING_ENABLED                        	YES
#define ACTION_VIEW_MAIN_BAR_ENABLED                                	YES
#define ACTION_VIEW_STATUS_BAR_ENABLED                              	YES
#define ACTION_VIEW_PAGE_BAR_ENABLED                                	YES
#define ACTION_VIEW_PERSONAL_BAR_ENABLED                            	YES
#define ACTION_VIEW_ADDRESS_BAR_ENABLED                             	YES
#define ACTION_VIEW_NAVIGATION_BAR_ENABLED                          	YES
#define ACTION_VIEW_PROGRESS_BAR_ENABLED                            	YES
#define ACTION_SET_VISIBILITY_ENABLED                               	YES
#define ACTION_SET_ALIGNMENT_ENABLED                                	YES
#define ACTION_SET_AUTO_ALIGNMENT_ENABLED                           	YES
#define ACTION_SET_WRAPPING_ENABLED                                 	YES
#define ACTION_SET_COLLAPSE_ENABLED                                 	YES
#define ACTION_ENABLE_LARGE_IMAGES_ENABLED                          	YES
#define ACTION_DISABLE_LARGE_IMAGES_ENABLED                         	YES
#define ACTION_SHOW_EDIT_DROPDOWN_ENABLED                           	YES
#define ACTION_SHOW_EXTENDER_POPUP_MENU_ENABLED                     	YES
#define ACTION_SHOW_OPERA_ENABLED                                   	YES
#define ACTION_HIDE_OPERA_ENABLED                                   	YES
#define ACTION_ACTIVATE_WINDOW_ENABLED                              	YES
#define ACTION_ACTIVATE_HOTLIST_WINDOW_ENABLED                      	YES
#define ACTION_SHOW_CONTEXT_MENU_ENABLED                            	YES
#define ACTION_SHOW_ACTIVE_BOOKMARK_MENU_ENABLED                    	YES
#define ACTION_GO_TO_PARENT_DIRECTORY_ENABLED                       	YES
#define ACTION_SHOW_ADDRESS_DROPDOWN_ENABLED                        	YES
#define ACTION_DELETE_SELECTED_ITEM_ENABLED               	         	YES
#define ACTION_FOCUS_ADDRESS_FIELD_ENABLED                          	YES
#define ACTION_FOCUS_SEARCH_FIELD_ENABLED                           	YES
#define ACTION_FOCUS_PERSONAL_BAR_ENABLED                           	YES
#define ACTION_FOCUS_QUICK_REPLY_ENABLED                            	YES
#define ACTION_FOCUS_CHAT_INPUT_ENABLED                             	YES
#define ACTION_CYCLE_TO_PREVIOUS_WINDOW_ENABLED                     	YES
#define ACTION_VALIDATE_DOCUMENT_SOURCE_ENABLED                     	YES
#define ACTION_VALIDATE_FRAME_SOURCE_ENABLED                        	YES
#define ACTION_ADD_LINK_TO_BOOKMARKS_ENABLED                        	YES
#define ACTION_ADD_LINK_TO_CONTACTS_ENABLED                         	YES
#define ACTION_MANAGE_CONTACTS_ENABLED                              	YES
#define ACTION_ENABLE_DISPLAY_IMAGES_ENABLED                        	YES
#define ACTION_DISPLAY_CACHED_IMAGES_ONLY_ENABLED                   	YES
#define ACTION_DISABLE_DISPLAY_IMAGES_ENABLED                       	YES
#define ACTION_NO_SECURITY_ENABLED                                  	YES
#define ACTION_LOW_SECURITY_ENABLED                                 	YES
#define ACTION_MEDIUM_SECURITY_ENABLED                              	YES
#define ACTION_HIGH_SECURITY_ENABLED                                	YES
#define ACTION_EXTENDED_SECURITY_ENABLED                               	YES
#define ACTION_TRUST_INFORMATION_ENABLED								YES
#define ACTION_TRUST_UNKNOWN_ENABLED									YES
#define ACTION_TRUST_FRAUD_ENABLED										YES
#define ACTION_DOWNLOAD_TRUST_PAGE_ENABLED								YES
#define ACTION_SHOW_MESSAGE_CONSOLE_ENABLED								YES
#define ACTION_STOP_TRANSFER_ENABLED                                	YES
#define ACTION_RESUME_TRANSFER_ENABLED                              	YES
#define ACTION_RESTART_TRANSFER_ENABLED                             	YES
#define ACTION_OPEN_TRANSFER_ENABLED                                	YES
#define ACTION_OPEN_TRANSFER_FOLDER_ENABLED                         	YES
#define ACTION_REMOVE_TRANSFER_ENABLED                              	YES
#define ACTION_REMOVE_ALL_FINISHED_TRANSFERS_ENABLED                	YES
#define ACTION_COPY_TRANSFER_INFO_ENABLED                           	YES
#define ACTION_SHOW_TRANSFERPANEL_DETAILS_ENABLED                   	YES
#define ACTION_HIDE_TRANSFERPANEL_DETAILS_ENABLED                   	YES
#define ACTION_SET_SHOW_TRANSFERWINDOW_ENABLED                      	YES
#define ACTION_SHOW_NEW_TRANSFERS_ON_TOP_ENABLED                    	YES
#define ACTION_SHOW_NEW_TRANSFERS_ON_BOTTOM_ENABLED                 	YES
#define ACTION_DOWNLOAD_URL_AS_ENABLED                              	YES
#define ACTION_CUSTOMIZE_TOOLBARS_ENABLED                           	YES
#define ACTION_SET_BUTTON_STYLE_ENABLED                             	YES
#define ACTION_ENABLE_SPECIAL_EFFECTS_ENABLED                       	YES
#define ACTION_DISABLE_SPECIAL_EFFECTS_ENABLED                      	YES
#define ACTION_LOCK_TOOLBARS_ENABLED                                	YES
#define ACTION_UNLOCK_TOOLBARS_ENABLED                              	YES
#define ACTION_LOCK_PANEL_ENABLED                                   	YES
#define ACTION_UNLOCK_PANEL_ENABLED                                 	YES
#define ACTION_SHOW_PANEL_ENABLED                                   	YES
#define ACTION_HIDE_PANEL_ENABLED                                   	YES
#define ACTION_FOCUS_PANEL_ENABLED                                  	YES
#define ACTION_SHOW_PANEL_TOGGLE_ENABLED                            	YES
#define ACTION_HIDE_PANEL_TOGGLE_ENABLED                            	YES
#define ACTION_ADD_WEB_LANGUAGE_ENABLED                             	YES
#define ACTION_MOVE_ITEM_UP_ENABLED                                 	YES
#define ACTION_MOVE_ITEM_DOWN_ENABLED                               	YES
#define ACTION_CHOOSE_SOUND_ENABLED                                 	YES
#define ACTION_TEST_SOUND_ENABLED                                   	YES
#define ACTION_CHOOSE_FONT_ENABLED                                  	YES
#define ACTION_CHOOSE_BACKGROUND_COLOR_ENABLED                      	YES
#define ACTION_CHOOSE_LINK_COLOR_ENABLED                            	YES
#define ACTION_CHOOSE_FONT_COLOR_ENABLED                            	YES
#define ACTION_SHOW_LINK_STYLE_ENABLED                              	YES
#define ACTION_SHOW_INTERNATIONAL_FONTS_ENABLED                     	YES
#define ACTION_NEW_FILE_TYPE_ENABLED                                	YES
#define ACTION_EDIT_FILE_TYPE_ENABLED                               	YES
#define ACTION_CHECK_ALL_ENABLED                                    	YES
#define ACTION_SHOW_PROXY_SERVERS_ENABLED                           	YES
#define ACTION_SHOW_NAME_COMPLETION_ENABLED                         	YES
#define ACTION_SHOW_SERVER_FILTERS_ENABLED                          	YES
#define ACTION_SHOW_SECURITY_PROTOCOLS_ENABLED                      	YES
#define ACTION_MENU_FOLDER_ENABLED                                  	YES
#define ACTION_NEW_SERVER_ENABLED                                   	YES
#define ACTION_ACCEPT_CERTIFICATE_ENABLED                           	YES
#define ACTION_INSTALL_CERTIFICATE_ENABLED                          	YES
#define ACTION_APPLY_ENABLED                                        	YES
#define ACTION_EXECUTE_TRANSFERITEM_ENABLED                         	YES
#define ACTION_SHOW_CERTIFICATE_DETAILS_ENABLED                     	YES
#define ACTION_DELETE_CERTIFICATE_ENABLED								YES
#define ACTION_IMPORT_CERTIFICATE_ENABLED								YES
#define ACTION_EXPORT_CERTIFICATE_ENABLED								YES
#define ACTION_CLEAR_DISK_CACHE_ENABLED                             	YES
#define ACTION_CLEAR_VISITED_HISTORY_ENABLED                        	YES
#define ACTION_CLEAR_TYPED_IN_HISTORY_ENABLED                       	YES
#define ACTION_VALIDATE_JAVA_PATH_ENABLED                           	YES
#define ACTION_FIND_PLUGINS_ENABLED                                 	YES
#define ACTION_SHOW_PLUGIN_PATH_SELECTOR_ENABLED                    	YES
#define ACTION_ACTIVATE_BUTTON_ENABLED                              	YES
#define ACTION_REPORT_SITE_PROBLEM_ENABLED                          	YES
#define ACTION_CHOOSE_CURRENT_PAGE_ENABLED                          	YES
#define ACTION_ENABLE_DELETE_PRIVATE_DATA_ENABLED                   	YES
#define ACTION_DISABLE_DELETE_PRIVATE_DATA_ENABLED                  	YES
#define ACTION_SHOW_ADVANCED_WINDOWS_OPTIONS_ENABLED                	YES
#define ACTION_SHOW_ATTACHMENTS_POPUP_ENABLED                       	YES
#define ACTION_SAVE_ATTACHMENT_LIST_TO_FOLDER_ENABLED               	YES
#define ACTION_SHOW_DEFAULT_APPLICATION_ENABLED                     	YES
#define ACTION_SHOW_LANGUAGE_PREFERENCES_ENABLED                    	YES
#define ACTION_HIGHLIGHT_BOOKMARK_ENABLED                           	YES
#define ACTION_HIGHLIGHT_NOTE_ENABLED                               	YES
#define ACTION_SET_PREFERENCE_ENABLED									YES
#define ACTION_SET_WIDGET_MODE_ENABLED							        YES
#define ACTION_CREATE_SEARCH_ENABLED							        YES
#define ACTION_CONTENTBLOCK_MODE_ON_ENABLED								YES
#define ACTION_CONTENTBLOCK_MODE_OFF_ENABLED							YES
#define ACTION_CONTENTBLOCK_ACCEPT_ENABLED								YES
#define ACTION_CONTENTBLOCK_CANCEL_ENABLED								YES
#define ACTION_CONTENTBLOCK_DETAILS_ENABLED								YES
#define	ACTION_EDIT_SITE_PREFERENCES_ENABLED							YES
#define ACTION_AUTOCOMPLETE_SERVER_NAME_ENABLED							YES
#define ACTION_OPEN_URL_IN_CURRENT_PAGE_ENABLED							YES
#define ACTION_OPEN_URL_IN_NEW_PAGE_ENABLED								YES
#define ACTION_OPEN_URL_IN_NEW_BACKGROUND_PAGE_ENABLED					YES
#define ACTION_OPEN_URL_IN_NEW_WINDOW_ENABLED							YES
#define ACTION_SET_WIDGET_STYLE_ENABLED									YES
#define ACTION_NEVER_ENABLED											YES
#define ACTION_MANAGE_SITES_ENABLED										YES
#define ACTION_RELOAD_STYLESHEETS_ENABLED								YES
#define ACTION_OPEN_WIDGET_ENABLED										YES
#define ACTION_CLOSE_WIDGET_ENABLED										YES
#define ACTION_RENAME_ENABLED                                    		YES
#define ACTION_SAVE_ATTACHMENT_TO_DOWNLOAD_FOLDER_ENABLED				YES
#define ACTION_NEXT_CHARACTER_SPATIAL_ENABLED							YES
#define ACTION_PREVIOUS_CHARACTER_SPATIAL_ENABLED						YES
#define ACTION_NEXT_LINE_SPATIAL_ENABLED								YES
#define ACTION_PREVIOUS_LINE_SPATIAL_ENABLED							YES
#define ACTION_THUMB_CLOSE_PAGE_ENABLED									YES
#define ACTION_THUMB_CONFIGURE_ENABLED									YES
#define ACTION_THUMB_EDIT_ENABLED										YES
#define ACTION_TOGGLE_HTML_EMAIL_ENABLED								YES
#define ACTION_EMAIL_TOGGLE_BOLD_ENABLED								YES
#define ACTION_EMAIL_TOGGLE_ITALIC_ENABLED								YES
#define ACTION_EMAIL_TOGGLE_UNDERLINE_ENABLED							YES
#define ACTION_EMAIL_TOGGLE_STRIKETHROUGH_ENABLED						YES
#define ACTION_EMAIL_SET_FONT_ENABLED									YES
#define ACTION_EMAIL_SET_SIZE_ENABLED									YES
#define ACTION_EMAIL_ADD_LINK_ENABLED									YES
#define ACTION_EMAIL_SET_COLOR_ENABLED									YES
#define ACTION_EMAIL_SET_SUPERSCRIPT_ENABLED							YES
#define ACTION_EMAIL_SET_SUBSCRIPT_ENABLED								YES
#define ACTION_EMAIL_INDENT_ENABLED										YES
#define ACTION_EMAIL_OUTDENT_ENABLED									YES
#define ACTION_EMAIL_SET_ORDERED_LIST_ENABLED							YES
#define ACTION_EMAIL_SET_UNORDERED_LIST_ENABLED							YES
#define ACTION_EMAIL_ALIGN_LEFT_ENABLED									YES
#define ACTION_EMAIL_ALIGN_CENTER_ENABLED								YES
#define ACTION_EMAIL_ALIGN_RIGHT_ENABLED								YES
#define ACTION_EMAIL_ALIGN_JUSTIFY_ENABLED								YES
#define ACTION_OVERRIDE_SCROLL_IS_PAN_ENABLED							YES
#define ACTION_GOTO_SPEEDDIAL_ENABLED									YES
#define ACTION_SPEEDDIAL_CLOSE_SEARCH_ENABLED							YES
#define ACTION_CHANGE_DIRECTION_AUTOMATIC_ENABLED						YES
#define ACTION_EMAIL_TOGGLE_HTML_TOOLBAR_ENABLED						YES
#define ACTION_PAN_X_ENABLED											YES
#define ACTION_PAN_Y_ENABLED											YES
#define ACTION_COMPOSITE_PAN_ENABLED									YES
#define ACTION_INSTALL_WIDGET_ENABLED									YES
#define ACTION_OPEN_MESSAGE_CONSOLE_FOR_MAIL_ENABLED					YES
#define ACTION_REOPEN_WINDOW_ENABLED                                  	YES
#define ACTION_RELOAD_THUMBNAIL_ENABLED									YES
#define ACTION_DISCARD_DRAFT_ENABLED									YES
#define ACTION_SEARCH_IN_MAIL_ENABLED									YES
#define ACTION_SHOW_SPEEDDIAL_CONTENTS_ENABLED							YES
#define ACTION_CLOSE_HELP_TOOLTIP_ENABLED								YES
#define ACTION_DELAY_ENABLED											YES
#define ACTION_GOTO_MESSAGE_ENABLED										YES
#define ACTION_MAKE_READABLE_ENABLED									YES
#define ACTION_SWITCH_GROUPS_ENABLED									YES
#define ACTION_OPEN_EXPAND_ENABLED										YES
#define ACTION_CLOSE_EXPAND_ENABLED										YES
#define ACTION_OPERA_UNITE_ENABLE_ENABLED								YES
#define ACTION_OPERA_UNITE_DISABLE_ENABLED								YES
#define ACTION_OPERA_UNITE_RESTART_ENABLED								YES
#define ACTION_SHOW_OPERA_UNITE_ROOT_ENABLED							YES
#define ACTION_SHOW_OPERA_UNITE_OPTIONS_ENABLED							YES
#define ACTION_OPERA_UNITE_ACCEPT_ENABLED								YES
#define ACTION_OPERA_UNITE_GOTO_PUBLIC_PAGE_ENABLED						YES
#define ACTION_DESKTOP_GADGET_CALLBACK_ENABLED                          YES
#define ACTION_DESKTOP_GADGET_CANCEL_CALLBACK_ENABLED                   YES
#define ACTION_OPEN_DEVTOOLS_WINDOW_ENABLED								YES
#define ACTION_CLOSE_DEVTOOLS_WINDOW_ENABLED							YES
#define ACTION_ATTACH_DEVTOOLS_WINDOW_ENABLED							YES
#define ACTION_DETACH_DEVTOOLS_WINDOW_ENABLED							YES
#define ACTION_MANAGE_WHITELIST_ENABLED                                 YES
#define ACTION_SHOW_CLASSIC_TAB_OPTIONS_ENABLED							YES
#define ACTION_INVITE_FRIENDS_ENABLED						            YES
#define ACTION_REMOVE_UNITE_USER_ENABLED						        YES
#define ACTION_ADD_UNITE_USER_ENABLED						            YES
#define ACTION_COPY_UNITE_ADDRESS_ENABLED						        YES
#define ACTION_OPEN_FILE_IN_ENABLED										YES
#define ACTION_OPEN_IMAGE_IN_ENABLED									YES
#define ACTION_MANAGE_SEARCH_ENGINES_ENABLED							YES
#define ACTION_ACCEPT_COOKIE_ENABLED									YES
#define ACTION_REFUSE_COOKIE_ENABLED									YES
#define ACTION_ADD_REMOVE_PANELS_ENABLED								YES
#define ACTION_ADD_USER_SEARCH_ENABLED									YES
#define ACTION_EDIT_USER_SEARCH_ENABLED									YES
#define ACTION_DELETE_USER_SEARCH_ENABLED								YES
#define ACTION_SELECT_ITEM_ENABLED										YES
#define ACTION_INTERNAL_SPELLCHECK_LANGUAGE_ENABLED						YES
#define ACTION_INTERNAL_SPELLCHECK_REPLACEMENT_ENABLED					YES
#define ACTION_INTERNAL_SPELLCHECK_ENABLE_ENABLED						YES
#define ACTION_INTERNAL_SPELLCHECK_ADD_WORD_ENABLED						YES
#define ACTION_INTERNAL_SPELLCHECK_IGNORE_WORD_ENABLED					YES
#define ACTION_INTERNAL_SPELLCHECK_REMOVE_WORD_ENABLED					YES
#define ACTION_WATCH_INDEX_ENABLED										YES
#define ACTION_STOP_WATCH_INDEX_ENABLED									YES
#define ACTION_IGNORE_INDEX_ENABLED										YES
#define ACTION_STOP_IGNORE_INDEX_ENABLED								YES
#define ACTION_WATCH_CONTACT_ENABLED									YES
#define ACTION_STOP_WATCH_CONTACT_ENABLED								YES
#define ACTION_IGNORE_CONTACT_ENABLED									YES
#define ACTION_STOP_IGNORE_CONTACT_ENABLED								YES
#define ACTION_GO_TO_THREAD_ENABLED										YES
#define ACTION_FETCH_COMPLETE_MESSAGE_ENABLED							YES
#define ACTION_FILTER_NOW_ENABLED										YES
#define ACTION_ENABLE_TEXT_SELECTION_ENABLED							YES
#define ACTION_DISABLE_TEXT_SELECTION_ENABLED							YES
#define ACTION_ENABLE_LOW_BANDWIDTH_MODE_ENABLED						YES
#define ACTION_DISABLE_LOW_BANDWIDTH_MODE_ENABLED						YES
#define ACTION_MINIMIZE_AUTO_UPDATE_DIALOG_ENABLED						YES
#define ACTION_RESTORE_AUTO_UPDATE_DIALOG_ENABLED						YES
#define ACTION_START_AUTO_UPDATE_ENABLED								YES	
#define ACTION_RESUME_AUTO_UPDATE_ENABLED								YES
#define ACTION_CANCEL_AUTO_UPDATE_ENABLED								YES
#define ACTION_RESTART_OPERA_ENABLED									YES
#define ACTION_EMAIL_INSERT_PICTURE_ENABLED                             YES
#define ACTION_EMAIL_INCREASE_TEXT_SIZE_ENABLED                         YES
#define ACTION_EMAIL_DECREASE_TEXT_SIZE_ENABLED                         YES
#define ACTION_EMAIL_INSERT_HORIZONTAL_RULE_ENABLED						YES
#define ACTION_EMAIL_INSERT_HTML_ENABLED                                YES
#define ACTION_BASIC_AUTHENTICATION_INFO_ENABLED						YES
#define ACTION_ARCHIVE_MESSAGE_ENABLED									YES
#define ACTION_START_HIGHLIGHT_ENABLED									YES
#define ACTION_OPEN_FONT_DIALOG_ENABLED									YES
#define ACTION_ENABLE_OPERA_WEB_TURBO_ENABLED							YES
#define ACTION_DISABLE_OPERA_WEB_TURBO_ENABLED							YES
#define ACTION_OPEN_OPERA_WEB_TURBO_DIALOG_ENABLED						YES
#define ACTION_SET_OPERA_WEB_TURBO_MODE_ENABLED							YES
#define ACTION_ABOUT_OPERA_WEB_TURBO_ENABLED							YES
#define ACTION_FEATURE_SETUP_CONTINUE_ENABLED							YES
#define ACTION_FEATURE_SETTINGS_CONTINUE_ENABLED						YES
#define ACTION_FEATURE_SETUP_CREATE_ACCOUNT_ENABLED						YES
#define ACTION_FEATURE_SETUP_SKIP_ACCOUNT_ENABLED						YES
#define ACTION_FEATURE_SETUP_NEW_ACCOUNT_ENABLED						YES
#define ACTION_FEATURE_SETUP_LOGIN_ENABLED								YES
#define ACTION_VIEW_FEATURE_LICENSE_ENABLED								YES
#define ACTION_ACCEPT_FEATURE_LICENSE_ENABLED							YES
#define ACTION_DECLINE_FEATURE_LICENSE_ENABLED							YES
#define ACTION_ACCOUNT_LOGOUT_ENABLED									YES
#define ACTION_FEATURE_CHANGE_ACCOUNT_ENABLED							YES
#define ACTION_DISPLAY_EXTERNAL_EMBEDS_ENABLED							YES
#define ACTION_SHOW_MAIL_LABEL_MENU_ENABLED								YES
#define ACTION_FULL_SYNC_ENABLED										YES
#ifdef SUPPORT_DATA_SYNC
#define ACTION_SET_UP_SYNC_ENABLED										YES
#define ACTION_OPEN_SYNC_SETTINGS_ENABLED								YES
#define ACTION_SHOW_SYNC_STATUS_ENABLED									YES
#endif // SUPPORT_DATA_SYNC
#ifdef WEBSERVER_SUPPORT
#define ACTION_SET_UP_WEBSERVER_ENABLED									YES
#define ACTION_OPEN_WEBSERVER_SETTINGS_ENABLED							YES
#define ACTION_SHOW_WEBSERVER_STATUS_ENABLED							YES
#define ACTION_OPEN_ADVANCED_WEBSERVER_SETTINGS_ENABLED					YES
#define ACTION_ENABLE_SERVICE_DISCOVERY_NOTIFICATIONS_ENABLED			YES
#define ACTION_DISABLE_SERVICE_DISCOVERY_NOTIFICATIONS_ENABLED			YES
#endif // WEBSERVER_SUPPORT
#define ACTION_OPEN_SIGNATURE_DIALOG_ENABLED                            YES
#define ACTION_EMAIL_CLEAR_FORMATTING_ENABLED							YES
#define ACTION_MAIL_SHOW_INDEX_ENABLED									YES
#define ACTION_MAIL_HIDE_INDEX_ENABLED									YES
#define ACTION_RESET_MAIL_PANEL_ENABLED									YES
#define ACTION_CHOOSE_LABEL_ICON_ENABLED								YES
#define	ACTION_CHOOSE_CUSTOM_ICON_ENABLED								YES
#define ACTION_SET_MAIL_SEARCH_TYPE_ENABLED								YES
#define ACTION_ADD_FILTER_FROM_SEARCH_ENABLED							YES

#ifdef INTERNAL_SPELLCHECK_SUPPORT
#define ACTION_INSTALL_SPELLCHECK_LANGUAGE_ENABLED                      YES
#define ACTION_UPDATE_SPELLCHECK_LANGUAGES_ENABLED						YES
#endif

#define ACTION_INVOKE_DIALOG_ENABLED                                    YES
#define ACTION_SELECT_ENABLED                                           YES
#define ACTION_RELOAD_SKIN_ENABLED										YES
#define ACTION_SHOW_MAIN_MENU_ENABLED									YES
#define ACTION_SHOW_MENU_ENABLED										YES
#define ACTION_SHOW_MENU_SECTION_ENABLED								YES
#define ACTION_OPEN_FOLDER_ENABLED										YES
#define ACTION_GO_TO_CYCLER_PAGE_ENABLED								YES
#define ACTION_SHOW_FINDTEXT_ENABLED									YES
#define ACTION_SEARCH_WRAPPED_ENABLED									YES
#define ACTION_SEARCH_NOT_FOUND_ENABLED									YES
#define ACTION_WAND_SAVE_ENABLED										YES
#define ACTION_WAND_NEVER_SAVE_ENABLED									YES
#define ACTION_ENABLE_TAB_THUMBNAILS_ENABLED							YES
#define ACTION_TOGGLE_TAB_THUMBNAILS_ENABLED							YES
#define ACTION_SHOW_SPEEDDIAL_GLOBAL_CONFIG_ENABLED						YES
#define ACTION_USE_IMAGE_AS_SPEEDDIAL_BACKGROUND_ENABLED                YES
#define ACTION_WIDGET_INSTALLER_INSTALL_ENABLED							YES
#define ACTION_WIDGET_INSTALLER_SETTINGS_ENABLED						YES
#define ACTION_INVOKE_ACCESS_KEY_ENABLED								YES
#define ACTION_SHOW_SEARCH_DROPDOWN_ENABLED								YES
#define ACTION_SET_PRIVACY_MODE_ENABLED									YES
#define ACTION_GO_TO_PRIVACY_INTRO_PAGE_ENABLED							YES
#define ACTION_CLEAR_SEARCH_FIELD_ENABLED								YES
#define ACTION_CLEAR_PREVIOUS_SEARCHES_ENABLED							YES
#define ACTION_CLOSE_ALL_PRIVATE_ENABLED								YES
#define ACTION_INSPECT_ELEMENT_ENABLED                              	YES
#define ACTION_SEARCH_FIELD_GO_ENABLED									YES
#define ACTION_FOLLOW_IMAGE_DESCRIPTION_URL_ENABLED						YES
#define ACTION_REPLY_TO_LIST_ENABLED									YES
#define ACTION_REPLY_TO_REPLYTO_ENABLED									YES
#define ACTION_REPLY_TO_SENDER_ENABLED									YES
#define ACTION_ACCEPT_WEBSTORAGE_QUOTA_REQUEST_ENABLED					YES
#define ACTION_REJECT_WEBSTORAGE_QUOTA_REQUEST_ENABLED					YES
#define ACTION_OPEN_ACCORDION_ITEM_ENABLED								YES
#define ACTION_CLOSE_ACCORDION_ITEM_ENABLED								YES
#define ACTION_REMOVE_FOLDER_ENABLED									YES
#define ACTION_SEARCH_IN_INDEX_ENABLED									YES
#define ACTION_FLAG_MESSAGE_ENABLED										YES
#define ACTION_EXPAND_MESSAGE_ENABLED									YES
#define ACTION_GROUP_MAILS_ENABLED										YES
#define ACTION_MEDIA_SEEK_FORWARD_ENABLED								YES
#define ACTION_MEDIA_SEEK_BACKWARD_ENABLED								YES
#define ACTION_MEDIA_PLAY_ENABLED										YES
#define ACTION_MEDIA_PAUSE_ENABLED										YES
#define ACTION_MEDIA_MUTE_ENABLED										YES
#define ACTION_MEDIA_UNMUTE_ENABLED										YES
#define ACTION_MEDIA_SHOW_CONTROLS_ENABLED								YES
#define ACTION_MEDIA_HIDE_CONTROLS_ENABLED								YES

//depends on WIDGET_RUNTIME_SUPPORT
#define ACTION_WIDGET_INSTALLER_INSTALL_ENABLED							YES
#define ACTION_WIDGET_INSTALLER_SETTINGS_ENABLED						YES
#define ACTION_WIDGET_INSTALLER_HELP_ENABLED							YES
#define ACTION_CLEAR_WIDGET_DATA_ENABLED								YES
#define ACTION_WIDGET_PREFERENCE_PANE_ENABLED							YES
#define ACTION_FORGET_WIDGET_PASSWORDS_ENABLED							YES
#define ACTION_WIDGET_REMOTE_DEBUG_ENABLED								YES
#define ACTION_IMPORT_GADGETS_ENABLED									YES	
#define ACTION_SELECT_NO_GADGETS_ENABLED								YES
#define ACTION_SELECT_ALL_GADGETS_ENABLED								YES
#define ACTION_UPGRADE_GADGETS_ENABLED									YES
#define ACTION_DOWNLOAD_MORE_WIDGETS_ENABLED							YES
#define ACTION_WIDGET_ABOUT_PAGE_ENABLED								YES
#define ACTION_WIDGET_DESCRIPTION_ENABLED								YES

#define ACTION_PERMISSION_ACCEPT_ENABLED								YES
#define ACTION_PERMISSION_DENY_ENABLED									YES

#define ACTION_ALWAYS_USE_WEBHANDLER_ENABLED							YES
#define ACTION_NEVER_USE_WEBHANDLER_ENABLED								YES
#define ACTION_DO_NOT_USE_WEBHANDLER_NOW_ENABLED						YES
#define ACTION_MANAGE_INSTALLED_WEB_FEEDS_ENABLED						YES

#define ACTION_PASTE_AND_GO_BACKGROUND_ENABLED							YES
#define ACTION_PASTE_SELECTION_AND_GO_ENABLED							YES
#define ACTION_PASTE_SELECTION_AND_GO_BACKGROUND_ENABLED				YES

#define ACTION_COPY_MEDIA_ADDRESS_ENABLED								YES
#define ACTION_SAVE_MEDIA_ENABLED										YES	

#define ACTION_DELETE_LOCAL_STORAGE_ENABLED								YES
#define ACTION_GO_TO_TYPED_ADDRESS_ENABLED								YES
#define ACTION_INITIATE_OPERA_INSTALLATION_ENABLED						YES

#define ACTION_CRASH_REPORT_ISSUE_ENABLED								YES
#define ACTION_CRASH_VIEW_REPORT_ENABLED								YES

// Only used by Macintosh
#define ACTION_SPECIAL_CHARACTERS_ENABLED								NO

// depends on GADGET_UPDATE_SUPPORT
#define ACTION_CONFIRM_GADGET_UPDATE_ENABLED							YES	
#define ACTION_UPDATE_GADGET_DELAY_ENABLED								YES
#define ACTION_SHOW_GADGET_UPDATE_ENABLED								YES

#define ACTION_SHOW_ADDRESSBAR_OVERLAY_ENABLED							YES
#define ACTION_ENABLE_FULL_URL_IN_ADDRESS_FIELD_ENABLED					YES
#define ACTION_DISABLE_FULL_URL_IN_ADDRESS_FIELD_ENABLED				YES

// depends on PLUGIN_AUTO_UPDATE
#define ACTION_PLUGIN_INSTALL_SHOW_DIALOG_ENABLED                       YES
#define ACTION_PLUGIN_INSTALL_RELOAD_PAGE_ENABLED                       YES
#define ACTION_PLUGIN_INSTALL_SHOW_EULA_ENABLED                         YES
#define ACTION_PLUGIN_INSTALL_START_DOWNLOAD_ENABLED                    YES
#define ACTION_PLUGIN_INSTALL_DONT_SHOW_TOOLBAR_ENABLED                 YES
#define ACTION_PLUGIN_INSTALL_CANCEL_DOWNLOAD_ENABLED                   YES
#define ACTION_PLUGIN_INSTALL_RETRY_DOWNLOAD_ENABLED                    YES
#define ACTION_PLUGIN_INSTALL_START_AUTO_ENABLED                        YES
#define ACTION_PLUGIN_INSTALL_START_MANUAL_ENABLED                      YES
#define ACTION_PLUGIN_INSTALL_GOTO_PAGE_ENABLED                         YES
#define ACTION_PLUGIN_INSTALL_OPEN_EXTERNALLY_ENABLED                   YES
#define ACTION_PLUGIN_INSTALL_CANCEL_INSTALL_ENABLED                    YES

// depends on ON_DEMAND_PLUGINS
#define ACTION_ACTIVATE_ON_DEMAND_PLUGINS_ENABLED						YES

#define ACTION_DISSOLVE_TAB_GROUP_ENABLED								YES
#define ACTION_CLOSE_TAB_GROUP_ENABLED									YES
#define ACTION_ACTIVATE_GROUP_WINDOW_ENABLED							YES

// 
#define ACTION_EXTENSION_ACTION_ENABLED 								YES
#define ACTION_MANAGE_EXTENSIONS_ENABLED 								YES
#define ACTION_UNINSTALL_EXTENSION_ENABLED 								YES
#define ACTION_DISABLE_EXTENSION_ENABLED 								YES
#define ACTION_DISABLE_SPEEDDIAL_EXTENSION_ENABLED 						YES
#define ACTION_ENABLE_EXTENSION_ENABLED 								YES
#define ACTION_SHOW_EXTENSION_OPTIONS_ENABLED 							YES
#define ACTION_SHOW_SPEEDDIAL_EXTENSION_OPTIONS_ENABLED 				YES
#define ACTION_EXTENSION_PRIVACY_ENABLED 								YES
#define ACTION_SHOW_EXTENSION_COGWHEEL_MENU_ENABLED 					YES
#define ACTION_GET_MORE_EXTENSIONS_ENABLED								YES
#define ACTION_CANCEL_EXTENSION_DOWNLOAD_ENABLED						YES
#define ACTION_EXTENSION_INSTALLER_INSTALL_ENABLED						YES
#define ACTION_INSTALL_SPEEDDIAL_EXTENSION_ENABLED						YES
#define ACTION_DEVTOOLS_RELOAD_EXTENSION_ENABLED						YES
#define ACTION_EXTENSION_BUTTON_DISABLE_ENABLED							YES
#define ACTION_EXTENSION_BUTTON_UNINSTALL_ENABLED						YES
#define ACTION_UPDATE_EXTENSION_ENABLED									YES
#define ACTION_RELOAD_EXTENSION_ENABLED									YES
#define ACTION_SHOW_ZOOM_POPUP_MENU_ENABLED								YES
#define ACTION_MANAGE_PROXY_EXCEPTION_LIST_ENABLED						YES
#define ACTION_TOGGLE_SYSTEM_FULLSCREEN_ENABLED							 NO
#define ACTION_UNDO_SKIN_INSTALL_ENABLED								YES
#define ACTION_FIND_MORE_SKINS_ENABLED									YES
#define ACTION_TOGGLE_KEYBOARD_SELECTION_ENABLED						YES
#define ACTION_RANGE_GO_TO_START_ENABLED								YES
#define ACTION_GO_TO_START_ENABLED										YES
#define ACTION_RANGE_GO_TO_LINE_START_ENABLED							YES
#define ACTION_GO_TO_LINE_START_ENABLED									YES
#define ACTION_RANGE_GO_TO_END_ENABLED									YES
#define ACTION_GO_TO_END_ENABLED										YES
#define ACTION_RANGE_GO_TO_LINE_END_ENABLED								YES
#define ACTION_GO_TO_LINE_END_ENABLED									YES
#define ACTION_RANGE_PAGE_UP_ENABLED									YES
#define ACTION_PAGE_UP_ENABLED											YES
#define ACTION_RANGE_PAGE_DOWN_ENABLED									YES
#define ACTION_PAGE_DOWN_ENABLED										YES
#define ACTION_RANGE_NEXT_CHARACTER_ENABLED								YES
#define ACTION_NEXT_CHARACTER_ENABLED									YES
#define ACTION_RANGE_PREVIOUS_CHARACTER_ENABLED							YES
#define ACTION_PREVIOUS_CHARACTER_ENABLED								YES
#define ACTION_RANGE_NEXT_WORD_ENABLED									YES
#define ACTION_NEXT_WORD_ENABLED										YES
#define ACTION_RANGE_PREVIOUS_WORD_ENABLED								YES
#define ACTION_PREVIOUS_WORD_ENABLED									YES
#define ACTION_RANGE_NEXT_LINE_ENABLED									YES
#define ACTION_NEXT_LINE_ENABLED										YES
#define ACTION_RANGE_PREVIOUS_LINE_ENABLED								YES
#define ACTION_PREVIOUS_LINE_ENABLED									YES
#define ACTION_RANGE_NEXT_PARAGRAPH_ENABLED								YES
#define ACTION_NEXT_PARAGRAPH_ENABLED									YES
#define ACTION_RANGE_PREVIOUS_PARAGRAPH_ENABLED							YES
#define ACTION_PREVIOUS_PARAGRAPH_ENABLED								YES
#define ACTION_SET_WINDOW_DECORATION_ENABLED							YES
#define ACTION_ADD_TO_STARTPAGE_ENABLED									YES
#define ACTION_REMOVE_FROM_STARTPAGE_ENABLED							YES
#define ACTION_ADD_TO_FAVORITES_ENABLED									YES
#define ACTION_REMOVE_FROM_FAVORITES_ENABLED							YES
#define ACTION_SET_PRIORITY_ENABLED										YES
#define ACTION_ADD_WEB_PANEL_ENABLED									YES
#ifdef _DEBUG
# define ACTION_DEBUG_INVALIDATION_ENABLED								YES
#else
# define ACTION_DEBUG_INVALIDATION_ENABLED								NO
#endif // _DEBUG

#define ACTION_COMPOSITE_PAN_STOP_ENABLED								YES

#define ACTION_SHARE_CONTENT_ENABLED									YES
#define ACTION_OPEN_ITEM_ENABLED										YES
#define ACTION_VIEWPANE_ITEM_REMOVE_ENABLED								YES
#define ACTION_RELOAD_THUMBNAIL_ENABLED									YES
#define ACTION_OPEN_COLLECTION_VIEW_SETTINGS_ENABLED					YES
#define ACTION_SORT_COLLECTION_VIEW_ENABLED								YES
#define ACTION_SWITCH_TO_THUMBNAIL_VIEW_ENABLED							YES
#define ACTION_SWITCH_TO_LIST_VIEW_ENABLED								YES

#define ACTION_CANCEL_WEBSTORAGE_QUOTA_REQUEST_ENABLED					YES

#endif // QUICK_ACTIONS_H
