// <-*- Mode: c++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*->
// <copyright header>

// <autogenerated modules/hardcore/scripts/generate_prefs.py>

// <PrefsCollection InitStaticData>

#ifdef DEBUG
// <PrefsCollection debug operator implementation>
#endif // DEBUG
