// <-*- Mode: c++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*->
// <copyright header>

// <autogenerated modules/prefs/prefsmanager/collections/make-prefs.py>

// <PrefsCollection enums>
