// <copyright header>

// <autogenerated features.pike>

// This .inl file is only supposed to be included by modules/about/src/operaabout.cpp.
// To modify, please modify the feature-thirdparty.x.x.txt and features-thirdparty_attributions.txt
// and run modules/hardcore/scrips/operasetup.py .

// <feature attribution strings>
