// <copyright header>

// <autogenerated features.pike>

// You need to define PRODUCT_FEATURE_FILE to be the path to the file where
// you set your features. Define each feature to either YES or NO.

#ifndef MODULES_HARDCORE_FEATURES_FEATURES_H
#define MODULES_HARDCORE_FEATURES_FEATURES_H

// Make sure YES and NO are set.

#define YES 1
#define NO 0

// Include default defines.

#include "modules/hardcore/features/features-default.h"

#ifndef PRODUCT_FEATURE_FILE
#error "PRODUCT_FEATURE_FILE not defined."
#endif // !PRODUCT_FEATURE_FILE

#include PRODUCT_FEATURE_FILE

// Deprecated or redesigned features goes here.

// <deprecated features>

// Make sure a choice has been made for all features.

// <feature choice check>

// Check conflicts

// <feature conflict check>

// Check dependencies.

// <feature dependency check>

// Turn on defines.

// <feature defines>

// Include actions file before generated_actions, so that tweaks and
// API imports/exports can depend on them to some degree.

#ifndef PRODUCT_ACTIONS_FILE
#error "PRODUCT_ACTIONS_FILE not defined."
#endif // !PRODUCT_ACTIONS_FILE

#include PRODUCT_ACTIONS_FILE

// Include tweaks and API:s
#include "modules/hardcore/base/tweaks_and_apis.h"

// Include actions
#include "modules/hardcore/actions/generated_actions.h"

// Include messages
#include "modules/hardcore/mh/generated_messages.h"

// Undefine YES and NO.

#undef YES
#undef NO

// Undefine all FEATURE_ defines.
// <feature undefines>

// Include features-post.h which turn on defines needed by other defines.

#include "modules/hardcore/features/features-post.h"

// <core version>

// <opera version>

// <module profiling>

#endif // !MODULES_HARDCORE_FEATURES_FEATURES_H
