#!/bin/bash
SCRIPTPATH="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
BASEPATH=${SCRIPTPATH%modules/database/*}

if [ "$SCRIPTPATH" = "$BASEPATH" ]; then
	echo "Run this script from inside the database module">&2
	exit
fi
cd "$BASEPATH/modules/database/src"
../../prefs/prefsmanager/collections/make-prefs.pl -b prefscollectiondatabase
