#!/bin/sh 

use_ip=false
resource=/keepalive/keepalive

[ $# -ge 2 ] || exit 2
webserver=$1
arg=$2

addr=$webserver

if [ "$use_ip" = "true" ]; then
  hostname=`echo $webserver | cut -d ':' -f 1`
  ip=`host $hostname | awk '{print $NF}'`
  ipcheck=`echo $ip | sed -e 's/\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)/rachmaninoff/'`
  if [ "$ipcheck" != "rachmaninoff" ]; then
      echo "$webserver DNS lookup failed for $hostname"
      exit 1
  fi
  addr=$ip
  port=`echo $webserver | cut -s -d ':' -f 2`
  if [ "$port" != "" ]; then
    addr="${ip}:${port}"
  fi
fi

if [ -d $webserver ]; then 
    rm -rf $webserver
fi
mkdir $webserver
cd $webserver

#while true; do 
#-t 3 -T 5 -q -t 1 -T 0 -O /dev/null --delete-after -a log
exec wget -t 1 -T 15 --header="Host: $webserver" --delete-after -nd -r -S -o log http://${addr}/ #${resource}\?${arg}
#     if [ $? -eq 0 ]; then
#         grep -q ^Downloaded log
# 	if [ $? -eq 0 ]; then
#             grep ^Downloaded log | grep -q 'in 1 files'
#             if [ $? -eq 0 ]; then
# 	        continue
# 	    fi
# 	fi
#     fi
    echo "$webserver bombed"
#     break
# done

