// <copyright header>

// <autogenerated modules/sqlite/mkwrappers.py>

#define COMPILING_SQLITE
#include "core/pch_system_includes.h"
#include "modules/sqlite/systemconfig.h"

#ifdef SQLITE_SUPPORT
// <original filename>
#endif // SQLITE_SUPPORT
