// <copyright header>

// <autogenerated make_properties.py>

#ifndef CSS_ALIASES_H
#define CSS_ALIASES_H
inline int GetAliasedProperty(int prop)
{
	switch (prop)
	{
// <switch aliased properties>
	default:
		return prop;
	}
}
#endif // CSS_ALIASES_H
