// <copyright header>

// <autogenerated make_properties.py>

#ifndef CSS_PROPERTIES_H
#define CSS_PROPERTIES_H

enum CSSProperty
{
// <property names>
};

// <properties length>

// <property name size>
// <property name max size>


/** Translate a property into its ::selection variant.
	Returns FALSE if the property is ignored for the ::selection pseudo element.
	Otherwise returns TRUE. */

inline BOOL PropertyToSelectionProperty(short& property)
{
	if (property == CSS_PROPERTY_color)
		property = CSS_PROPERTY_selection_color;
	else if (property == CSS_PROPERTY_background_color)
		property = CSS_PROPERTY_selection_background_color;
	else
		return FALSE;

	return TRUE;
}
#endif // CSS_PROPERTIES_H
