// <copyright header>

// <autogenerated make_values.py>

#ifndef CSS_VALUE_STRINGS_H
#define CSS_VALUE_STRINGS_H

#include "modules/style/src/css_values.h"

const short CSS_value_idx[] =
{
	// <CSS value idx>
};

CONST_ARRAY(g_css_value_name, uni_char*)
	// <CSS value name>
CONST_END(g_css_value_name)

const short CSS_value_tok[] =
{
	// <CSS value tok>
};

#endif // CSS_VALUE_STRINGS_H
