COMPILEJS=../../compilejs/debug_unicode/compilejs.exe

all:
	$(COMPILEJS) --quiet md5.js
	$(COMPILEJS) --quiet longstring.js
	$(COMPILEJS) --quiet fatstring.js
	$(COMPILEJS) --quiet unicode.js
	$(COMPILEJS) --quiet DecisionMaker.js

clean:
	rm -f *.jsobj
