// This file is generated by makelang.pl and should NOT be edited directly.

/** Version number for the string database sources.
 * This number is matched to the external *.lng files to ensure that the
 * file is consistent with what Opera is expecting.
 */
#define LANGUAGE_DATABASE_VERSION 884
