// <copyright header>

// <autogenerated actions.pike>

// To change this file, change module.actions for the appropriate module
// and run operasetup.py.
// You need to define PRODUCT_ACTIONS_FILE to be the path to the file where
// you decide whether actions are turned on or off.

enum Action
{
	ACTION_UNKNOWN = 0,
	// <actions_enum>

	LAST_ACTION,						///< must be last one of named actions. decides how many action strings we need
	ACTION_GET_ACTION_STATE,			///< sent to query the current stack of input contexts of the state of a certain action
	ACTION_GET_TYPED_OBJECT,
	ACTION_LOWLEVEL_KEY_DOWN,
	ACTION_LOWLEVEL_KEY_UP,
	ACTION_LOWLEVEL_KEY_PRESSED,
	ACTION_LOWLEVEL_NEW_KEYBOARD_CONTEXT,
	ACTION_LOWLEVEL_NEW_MOUSE_CONTEXT,
	ACTION_LOWLEVEL_PREFILTER_ACTION,	// all actions are sent as a parameter for this ACTION_LOWLEVEL_PREFILTER_ACTION first
};
