// <copyright header>

// Please don't modify this file.

// This file is automatically generated by actions.pike.
// To change this file, change module.actions for the appropriate module
// and run actions.pike.
// You need to define PRODUCT_ACTIONS_FILE to be the path to the file where
// you decide whether actions are turned on or off.

#ifndef MODULES_HARDCORE_ACTIONS_ACTIONS_H
#define MODULES_HARDCORE_ACTIONS_ACTIONS_H

// <actions>

#endif // !MODULES_HARDCORE_ACTIONS_ACTIONS_H
