// <copyright header>

// <autogenerated viewers.pike>

// To change this file, change module/viewers/module.viewers, and run
// the script module/viewers/src/viewers.pike

enum ViewersEnum { 

	// <viewers_enum>
	
	VIEWER_LAST
};
