/**************************************************
 * This file is generated by the script mktags_omf.pl
 * found in the <logdoc>/scripts directory
 *
 *     !!! DO NOT EDIT THIS FILE BY HAND !!!
 *
 * All changes will be lost when the files are 
 * generated again. (stighal, 2005-01-06)
 **************************************************/

#ifndef OMFENUM_H
#define OMFENUM_H

#include "modules/logdoc/markup.h"

#define OMF_ElementType Markup::Type
#define OMF_AttrType Markup::AttrType

#define OE_UNKNOWN Markup::HTE_UNKNOWN
#define OE_N Markup::OMFE_N
#define OE_V Markup::OMFE_V
#define OE_P Markup::OMFE_P
#define OE_L Markup::OMFE_L
#define OE_QL Markup::OMFE_QL
#define OE_HDR Markup::OMFE_HDR
#define OE_DIV Markup::OMFE_DIV
#define OE_SIG Markup::OMFE_SIG
#define OE_BODY Markup::OMFE_BODY
#define OE_MIME Markup::OMFE_MIME
#define OE_HGRP Markup::OMFE_HGRP
#define OE_ITEM Markup::OMFE_ITEM
#define OE_ICON Markup::OMFE_ICON
#define OE_ATTACH Markup::OMFE_ATTACH
#define OE_RFC822 Markup::OMFE_RFC822
#define OE_HEADERS Markup::OMFE_HEADERS
#define OE_HDRICON Markup::OMFE_HDRICON
#define OE_CAPTION Markup::OMFE_CAPTION
#define OE_FILENAME Markup::OMFE_FILENAME
#define OE_SHOWHEADERS Markup::OMFE_SHOWHEADERS

#endif /* OMFENUM_H */
