/**************************************************
 * This file is generated by the script mktags_wml.pl
 * found in the <logdoc>/scripts directory
 *
 *     !!! DO NOT EDIT THIS FILE BY HAND !!!
 *
 * All changes will be lost when the files are 
 * generated again. (maritb, 2005-01-06)
 **************************************************/

#ifndef WMLENUM_H
#define WMLENUM_H

#include "modules/logdoc/markup.h"

#define WML_ElementType Markup::Type

#define WE_UNKNOWN Markup::HTE_UNKNOWN
#define WE_DO Markup::WMLE_DO
#define WE_GO Markup::WMLE_GO
#define WE_WML Markup::WMLE_WML
#define WE_CARD Markup::WMLE_CARD
#define WE_NOOP Markup::WMLE_NOOP
#define WE_PREV Markup::WMLE_PREV
#define WE_TIMER Markup::WMLE_TIMER
#define WE_ACCESS Markup::WMLE_ACCESS
#define WE_ANCHOR Markup::WMLE_ANCHOR
#define WE_SETVAR Markup::WMLE_SETVAR
#define WE_WIDGET Markup::WMLE_WIDGET
#define WE_ONEVENT Markup::WMLE_ONEVENT
#define WE_REFRESH Markup::WMLE_REFRESH
#define WE_TEMPLATE Markup::WMLE_TEMPLATE
#define WE_POSTFIELD Markup::WMLE_POSTFIELD

#define WML_AttrType Markup::AttrType

#define WA_NULL Markup::HA_NULL
#define WA_UNKNOWN Markup::HA_XML
#define WA_ID Markup::WMLA_ID
#define WA_HREF Markup::WMLA_HREF
#define WA_TYPE Markup::WMLA_TYPE
#define WA_NAME Markup::WMLA_NAME
#define WA_MODE Markup::WMLA_MODE
#define WA_PATH Markup::WMLA_PATH
#define WA_CLASS Markup::WMLA_CLASS
#define WA_TITLE Markup::WMLA_TITLE
#define WA_VALUE Markup::WMLA_VALUE
#define WA_LABEL Markup::WMLA_LABEL
#define WA_INAME Markup::WMLA_INAME
#define WA_FORUA Markup::WMLA_FORUA
#define WA_METHOD Markup::WMLA_METHOD
#define WA_ONPICK Markup::WMLA_ONPICK
#define WA_FORMAT Markup::WMLA_FORMAT
#define WA_IVALUE Markup::WMLA_IVALUE
#define WA_DOMAIN Markup::WMLA_DOMAIN
#define WA_EMPTYOK Markup::WMLA_EMPTYOK
#define WA_ONTIMER Markup::WMLA_ONTIMER
#define WA_ENCTYPE Markup::WMLA_ENCTYPE
#define WA_ORDERED Markup::WMLA_ORDERED
#define WA_TABINDEX Markup::WMLA_TABINDEX
#define WA_MULTIPLE Markup::WMLA_MULTIPLE
#define WA_LOCALSRC Markup::WMLA_LOCALSRC
#define WA_OPTIONAL Markup::WMLA_OPTIONAL
#define WA_XMLLANG Markup::WMLA_XMLLANG
#define WA_ACCESSKEY Markup::WMLA_ACCESSKEY
#define WA_XMLSPACE Markup::WMLA_XMLSPACE
#define WA_NEWCONTEXT Markup::WMLA_NEWCONTEXT
#define WA_SENDREFERER Markup::WMLA_SENDREFERER
#define WA_CACHE_CONTROL Markup::WMLA_CACHE_CONTROL
#define WA_ONENTERFORWARD Markup::WMLA_ONENTERFORWARD
#define WA_ACCEPT_CHARSET Markup::WMLA_ACCEPT_CHARSET
#define WA_ONENTERBACKWARD Markup::WMLA_ONENTERBACKWARD

#endif /* WMLENUM_H */
