// <-*- Mode: c++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*->
// <copyright header>

// <autogenerated opera.py>

#ifndef OPERA_COMPONENTS_H
#define OPERA_COMPONENTS_H

enum OpComponentType {
	// <component identifiers>
	COMPONENT_LAST
};

#endif /* OPERA_COMPONENTS_H */
