// <copyright header>

// <autogenerated tweaks.pike>

// You need to define PRODUCT_TWEAKS_FILE to be the path to the file where
// you set your tweak values. For each tweak, first decide if you want to change
// the default value. If you want to change it, set the define.

#ifndef MODULES_HARDCORE_TWEAKS_TWEAKS_H
#define MODULES_HARDCORE_TWEAKS_TWEAKS_H

#ifndef PRODUCT_TWEAKS_FILE
#error "PRODUCT_TWEAKS_FILE not defined."
#endif // !PRODUCT_TWEAKS_FILE

#include PRODUCT_TWEAKS_FILE

// <tweaks>

// Include API's
#include "modules/hardcore/api/api.h"

// Undefine all TWEAK_ defines
// <tweak undefines>

#endif // !MODULES_HARDCORE_TWEAKS_TWEAKS_H
