// <copyright header>

// <autogenerated messages.pike>

#ifndef MODULES_HARDCORE_MH_MESSAGES_GENERATED_H
#define MODULES_HARDCORE_MH_MESSAGES_GENERATED_H

enum OpMessage
{
	MSG_NO_MESSAGE,

// <messages>

	MSG_LAST_MESSAGE
};

#ifdef MESSAGE_NAMES
// <has message macros>
#endif // MESSAGE_NAMES

#endif // !MODULES_HARDCORE_MESSAGES_MESSAGES_GENERATED_H
