// <copyright header>

// <autogenerated modules/logdoc/scripts/mkmarkup.py>

char const g_html5_attr_names[] = {
	// <nametable>
};

const unsigned g_html5_attr_indices[] = {
	// <indextable>
};

CONST_ARRAY(g_html5_attr_names_upper, uni_char*)
	// <uppernametable>
CONST_END(g_html5_attr_names_upper)
