// <copyright header>

// <autogenerated modules/logdoc/scripts/mkmarkup.py>

// <lengthconsts>

enum AttrType
{
	HA_NULL
	// <normaltypes>
	// <specialtypes>
	, HA_ABSOLUTELY_LAST
	// <delimiters>
};
