// <copyright header>

// <autogenerated modules/logdoc/scripts/mkmarkup.py>

// <lengthconsts>

enum Type
{
	HTE_DOC_ROOT
	// <normaltypes>
	, HTE_TEXT
	, HTE_TEXTGROUP
	, HTE_CDATA
	, HTE_COMMENT
	, HTE_DOCTYPE
	, HTE_ENTITY
	, HTE_ENTITYREF
	, HTE_PROCINST
	, HTE_UNKNOWNDECL
	// <specialtypes>
	, HTE_ABSOLUTELY_LAST
	// <delimiters>
};
