// token properties
const TP_NORMAL = 0;
const TP_INLINE = 1;
const TP_TABLE = 2;
const TP_MOD = 4;

// token contents
const TC_NONE = 0;
const TC_ATTRS = 1;
const TC_CONTENT = 2;
const TC_ATTRS_AND_CONTENT = 3;

var tokens = [
["WML Elements", [
    ["pre", "1b", TP_MOD, TC_NONE],
	["a", "1c", TP_MOD, TC_NONE],
	["td", "1d", TP_MOD, TC_NONE],
	["tr", "1e", TP_MOD, TC_NONE],
	["table", "1f", TP_MOD, TC_NONE],
	["p", "20", TP_MOD, TC_NONE],
	["postfield", "21", TP_MOD, TC_NONE],
	["anchor", "22", TP_MOD, TC_NONE],
	["access", "23", TP_MOD, TC_NONE],
	["b", "24", TP_MOD, TC_NONE],
	["big", "25", TP_MOD, TC_NONE],
	["br", "26", TP_MOD, TC_NONE],
	["card", "27", TP_MOD, TC_NONE],
	["do", "28", TP_MOD, TC_NONE],
	["em", "29", TP_MOD, TC_NONE],
	["fieldset", "2a", TP_MOD, TC_NONE],
	["go", "2b", TP_MOD, TC_NONE],
	["head", "2c", TP_MOD, TC_NONE],
	["i", "2d", TP_MOD, TC_NONE],
	["img", "2e", TP_MOD, TC_NONE],
	["input", "2f", TP_MOD, TC_NONE],
	["meta", "30", TP_MOD, TC_NONE],
	["noop", "31", TP_MOD, TC_NONE],
	["prev", "32", TP_MOD, TC_NONE],
	["onevent", "33", TP_MOD, TC_NONE],
	["optgroup", "34", TP_MOD, TC_NONE],
	["option", "35", TP_MOD, TC_NONE],
	["refresh", "36", TP_MOD, TC_NONE],
	["select", "37", TP_MOD, TC_NONE],
	["small", "38", TP_MOD, TC_NONE],
	["strong", "39", TP_MOD, TC_NONE],
	["template", "3b", TP_MOD, TC_NONE],
	["timer", "3c", TP_MOD, TC_NONE],
	["u", "3d", TP_MOD, TC_NONE],
	["setvar", "3e", TP_MOD, TC_NONE],
	["wml", "3f", TP_MOD, TC_NONE]]
], ["WML Attribute start", [
    ["accept-charset=\"", "05", TP_NORMAL, TC_NONE],
	["align=\"bottom", "06", TP_NORMAL, TC_NONE],
	["align=\"center", "07", TP_NORMAL, TC_NONE],
	["align=\"left", "08", TP_NORMAL, TC_NONE],
	["align=\"middle", "09", TP_NORMAL, TC_NONE],
	["align=\"right", "0a", TP_NORMAL, TC_NONE],
	["align=\"top", "0b", TP_NORMAL, TC_NONE],
	["alt=\"", "0c", TP_NORMAL, TC_NONE],
	["content=\"", "0d", TP_NORMAL, TC_NONE],
	["domain=\"", "0f", TP_NORMAL, TC_NONE],
	["emptyok=\"false", "10", TP_NORMAL, TC_NONE],
	["emptyok=\"true", "11", TP_NORMAL, TC_NONE],
	["format=\"", "12", TP_NORMAL, TC_NONE],
	["height=\"", "13", TP_NORMAL, TC_NONE],
	["hspace=\"", "14", TP_NORMAL, TC_NONE],
	["ivalue=\"", "15", TP_NORMAL, TC_NONE],
	["iname=\"", "16", TP_NORMAL, TC_NONE],
	["label=\"", "18", TP_NORMAL, TC_NONE],
	["localsrc=\"", "19", TP_NORMAL, TC_NONE],
	["maxlength=\"", "1a", TP_NORMAL, TC_NONE],
	["method=\"get", "1b", TP_NORMAL, TC_NONE],
	["method=\"post", "1c", TP_NORMAL, TC_NONE],
	["mode=\"nowrap", "1d", TP_NORMAL, TC_NONE],
	["mode=\"wrap", "1e", TP_NORMAL, TC_NONE],
	["multiple=\"false", "1f", TP_NORMAL, TC_NONE],
	["multiple=\"true", "20", TP_NORMAL, TC_NONE],
	["name=\"", "21", TP_NORMAL, TC_NONE],
	["newcontext=\"false", "22", TP_NORMAL, TC_NONE],
	["newcontext=\"true", "23", TP_NORMAL, TC_NONE],
	["onpick=\"", "24", TP_NORMAL, TC_NONE],
	["onenterbackward=\"", "25", TP_NORMAL, TC_NONE],
	["onenterforward=\"", "26", TP_NORMAL, TC_NONE],
	["ontimer=\"", "27", TP_NORMAL, TC_NONE],
	["optional=\"false", "28", TP_NORMAL, TC_NONE],
	["optional=\"true", "29", TP_NORMAL, TC_NONE],
	["path=\"", "2a", TP_NORMAL, TC_NONE],
	["scheme=\"", "2e", TP_NORMAL, TC_NONE],
	["sendreferer=\"false", "2f", TP_NORMAL, TC_NONE],
	["sendreferer=\"true", "30", TP_NORMAL, TC_NONE],
	["size=\"", "31", TP_NORMAL, TC_NONE],
	["src=\"", "32", TP_NORMAL, TC_NONE],
	["ordered=\"true", "33", TP_NORMAL, TC_NONE],
	["ordered=\"false", "34", TP_NORMAL, TC_NONE],
	["tabindex=\"", "35", TP_NORMAL, TC_NONE],
	["title=\"", "36", TP_NORMAL, TC_NONE],
	["type=\"", "37", TP_NORMAL, TC_NONE],
	["type=\"accept", "38", TP_NORMAL, TC_NONE],
	["type=\"delete", "39", TP_NORMAL, TC_NONE],
	["type=\"help", "3a", TP_NORMAL, TC_NONE],
	["type=\"password", "3b", TP_NORMAL, TC_NONE],
	["type=\"onpick", "3c", TP_NORMAL, TC_NONE],
	["type=\"onenterbackward", "3d", TP_NORMAL, TC_NONE],
	["type=\"onenterforward", "3e", TP_NORMAL, TC_NONE],
	["type=\"ontimer", "3f", TP_NORMAL, TC_NONE],
	["type=\"options", "45", TP_NORMAL, TC_NONE],
	["type=\"prev", "46", TP_NORMAL, TC_NONE],
	["type=\"reset", "47", TP_NORMAL, TC_NONE],
	["type=\"text", "48", TP_NORMAL, TC_NONE],
	["type=\"vnd.", "49", TP_NORMAL, TC_NONE],
	["href=\"", "4a", TP_NORMAL, TC_NONE],
	["href=\"http://", "4b", TP_NORMAL, TC_NONE],
	["href=\"https://", "4c", TP_NORMAL, TC_NONE],
	["value=\"", "4d", TP_NORMAL, TC_NONE],
	["vspace=\"", "4e", TP_NORMAL, TC_NONE],
	["width=\"", "4f", TP_NORMAL, TC_NONE],
	["xml:lang=\"", "50", TP_NORMAL, TC_NONE],
	["align=\"", "52", TP_NORMAL, TC_NONE],
	["columns=\"", "53", TP_NORMAL, TC_NONE],
	["class=\"", "54", TP_NORMAL, TC_NONE],
	["id=\"", "55", TP_NORMAL, TC_NONE],
	["forua=\"false", "56", TP_NORMAL, TC_NONE],
	["forua=\"true", "57", TP_NORMAL, TC_NONE],
	["src=\"http://", "58", TP_NORMAL, TC_NONE],
	["src=\"https://", "59", TP_NORMAL, TC_NONE],
	["http-equiv=\"", "5a", TP_NORMAL, TC_NONE],
	["http-equiv=\"Content-Type", "5b", TP_NORMAL, TC_NONE],
	["content=\"application/vnd.wap.wmlc;charset=", "5c", TP_NORMAL, TC_NONE],
	["http-equiv=\"Expires", "5d", TP_NORMAL, TC_NONE],
	["accesskey=\"", "5e", TP_NORMAL, TC_NONE],
	["enctype=\"", "5f", TP_NORMAL, TC_NONE],
	["enctype=\"application/x-www-form-urlencoded", "60", TP_NORMAL, TC_NONE],
	["enctype=\"multipart/form-data", "61", TP_NORMAL, TC_NONE],
	["xml:space=\"preserve", "62", TP_NORMAL, TC_NONE],
	["xml:space=\"default", "63", TP_NORMAL, TC_NONE],
	["cache-control=\"no-cache", "64", TP_NORMAL, TC_NONE]]
], ["WML Attribute value", [
	[".com/", "85", TP_NORMAL, TC_NONE],
	[".edu/", "86", TP_NORMAL, TC_NONE],
	[".net/", "87", TP_NORMAL, TC_NONE],
	[".org/", "88", TP_NORMAL, TC_NONE],
	["accept", "89", TP_NORMAL, TC_NONE],
	["bottom", "8a", TP_NORMAL, TC_NONE],
	["clear", "8b", TP_NORMAL, TC_NONE],
	["delete", "8c", TP_NORMAL, TC_NONE],
	["help", "8d", TP_NORMAL, TC_NONE],
	["http://", "8e", TP_NORMAL, TC_NONE],
	["http://www.", "8f", TP_NORMAL, TC_NONE],
	["https://", "90", TP_NORMAL, TC_NONE],
	["https://www.", "91", TP_NORMAL, TC_NONE],
	["middle", "93", TP_NORMAL, TC_NONE],
	["nowrap", "94", TP_NORMAL, TC_NONE],
	["onpick", "95", TP_NORMAL, TC_NONE],
	["onenterbackward", "96", TP_NORMAL, TC_NONE],
	["onenterforward", "97", TP_NORMAL, TC_NONE],
	["ontimer", "98", TP_NORMAL, TC_NONE],
	["options", "99", TP_NORMAL, TC_NONE],
	["password", "9a", TP_NORMAL, TC_NONE],
	["reset", "9b", TP_NORMAL, TC_NONE],
	["text", "9d", TP_NORMAL, TC_NONE],
	["top", "9e", TP_NORMAL, TC_NONE],
	["unknown", "9f", TP_NORMAL, TC_NONE],
	["wrap", "a0", TP_NORMAL, TC_NONE],
	["Www.", "a1", TP_NORMAL, TC_NONE]]
], ["Special WBXML", [
	["Switch page", "00", TP_INLINE, TC_NONE],
    ["End", "01", TP_NORMAL, TC_NONE],
	["Entity", "02", TP_INLINE, TC_NONE],
	["String, inline", "03", TP_INLINE, TC_NONE],
	["Literal, empty", "04", TP_TABLE, TC_NONE],
	["Extension 1, inline", "40", TP_INLINE, TC_NONE],
	["Extension 2, inline", "41", TP_INLINE, TC_NONE],
	["Extension 3, inline", "42", TP_INLINE, TC_NONE],
	["PI", "43", TP_INLINE, TC_NONE],
	["Literal, content", "44", TP_TABLE, TC_CONTENT],
	["Extension 1, table", "80", TP_TABLE, TC_NONE],
	["Extension 2, table", "81", TP_TABLE, TC_NONE],
	["Extension 3, table", "82", TP_TABLE, TC_NONE],
	["String, table", "83", TP_TABLE, TC_NONE],
	["Literal, attributes", "84", TP_TABLE, TC_ATTRS],
	["Extension 1, empty", "c0", TP_NORMAL, TC_NONE],
	["Extension 2, empty", "c1", TP_NORMAL, TC_NONE],
	["Extension 3, empty", "c2", TP_NORMAL, TC_NONE],
	["Opaque", "c3", TP_INLINE, TC_NONE],
	["Literal, attrs and content", "c4", TP_TABLE, TC_ATTRS_AND_CONTENT]]
]];
