/* -*- Mode: c++; tab-width: 4; c-basic-offset: 4 -*-
 * Copyright Opera Software 2007, do not distribute.
 */
#define ENABLE_OP_KEY_F1    				YES
#define ENABLE_OP_KEY_F2					YES
#define ENABLE_OP_KEY_F3					YES
#define ENABLE_OP_KEY_F4					YES
#define ENABLE_OP_KEY_F5					YES
#define ENABLE_OP_KEY_F6					YES
#define ENABLE_OP_KEY_F7					YES
#define ENABLE_OP_KEY_F8					YES
#define ENABLE_OP_KEY_F9					YES
#define ENABLE_OP_KEY_F10					YES
#define ENABLE_OP_KEY_F11					YES
#define ENABLE_OP_KEY_F12					YES
#if defined(_UNIX_DESKTOP_)
#define ENABLE_OP_KEY_F13					YES
#define ENABLE_OP_KEY_F14					YES
#define ENABLE_OP_KEY_F15					YES
#define ENABLE_OP_KEY_F16					YES
#define ENABLE_OP_KEY_F17					YES
#define ENABLE_OP_KEY_F18					YES
#define ENABLE_OP_KEY_F19					YES
#define ENABLE_OP_KEY_F20					YES
#define ENABLE_OP_KEY_F21					YES
#define ENABLE_OP_KEY_F22					YES
#define ENABLE_OP_KEY_F23					YES
#define ENABLE_OP_KEY_F24					YES
#define ENABLE_OP_KEY_F25					YES
#define ENABLE_OP_KEY_F26					YES
#define ENABLE_OP_KEY_F27					YES
#define ENABLE_OP_KEY_F28					YES
#define ENABLE_OP_KEY_F29					YES
#define ENABLE_OP_KEY_F30					YES
#define ENABLE_OP_KEY_F31					YES
#define ENABLE_OP_KEY_F32					YES
#define ENABLE_OP_KEY_F33					YES
#define ENABLE_OP_KEY_F34					YES
#define ENABLE_OP_KEY_F35					YES
#define ENABLE_OP_KEY_F36					YES
#else
#define ENABLE_OP_KEY_F13					NO
#define ENABLE_OP_KEY_F14					NO
#define ENABLE_OP_KEY_F15					NO
#define ENABLE_OP_KEY_F16					NO
#define ENABLE_OP_KEY_F17					NO
#define ENABLE_OP_KEY_F18					NO
#define ENABLE_OP_KEY_F19					NO
#define ENABLE_OP_KEY_F20					NO
#define ENABLE_OP_KEY_F21					NO
#define ENABLE_OP_KEY_F22					NO
#define ENABLE_OP_KEY_F23					NO
#define ENABLE_OP_KEY_F24					NO
#define ENABLE_OP_KEY_F25					NO
#define ENABLE_OP_KEY_F26					NO
#define ENABLE_OP_KEY_F27					NO
#define ENABLE_OP_KEY_F28					NO
#define ENABLE_OP_KEY_F29					NO
#define ENABLE_OP_KEY_F30					NO
#define ENABLE_OP_KEY_F31					NO
#define ENABLE_OP_KEY_F32					NO
#define ENABLE_OP_KEY_F33					NO
#define ENABLE_OP_KEY_F34					NO
#define ENABLE_OP_KEY_F35					NO
#define ENABLE_OP_KEY_F36					NO
#endif

#define ENABLE_OP_KEY_HOME					YES
#define ENABLE_OP_KEY_END					YES
#define ENABLE_OP_KEY_PAGEUP				YES
#define ENABLE_OP_KEY_PAGEDOWN				YES
#define ENABLE_OP_KEY_UP					YES
#define ENABLE_OP_KEY_DOWN					YES
#define ENABLE_OP_KEY_LEFT					YES
#define ENABLE_OP_KEY_RIGHT					YES
#define ENABLE_OP_KEY_ESC					YES

#define ENABLE_OP_KEY_OEM_1                 YES
#define ENABLE_OP_KEY_OEM_PLUS              YES
#define ENABLE_OP_KEY_OEM_COMMA             YES
#define ENABLE_OP_KEY_OEM_MINUS             YES
#define ENABLE_OP_KEY_OEM_PERIOD            YES
#define ENABLE_OP_KEY_OEM_2                 YES
#define ENABLE_OP_KEY_OEM_3                 YES
#define ENABLE_OP_KEY_OEM_4                 YES
#define ENABLE_OP_KEY_OEM_5                 YES
#define ENABLE_OP_KEY_OEM_6                 YES
#define ENABLE_OP_KEY_OEM_7                 YES
#define ENABLE_OP_KEY_OEM_8                 YES
#define ENABLE_OP_KEY_OEM_102               YES
#define ENABLE_OP_KEY_PROCESSKEY            YES
#define ENABLE_OP_KEY_UNICODE               YES

#define ENABLE_OP_KEY_NUMPAD0               YES
#define ENABLE_OP_KEY_NUMPAD1               YES
#define ENABLE_OP_KEY_NUMPAD2               YES
#define ENABLE_OP_KEY_NUMPAD3               YES
#define ENABLE_OP_KEY_NUMPAD4               YES
#define ENABLE_OP_KEY_NUMPAD5               YES
#define ENABLE_OP_KEY_NUMPAD6               YES
#define ENABLE_OP_KEY_NUMPAD7               YES
#define ENABLE_OP_KEY_NUMPAD8               YES
#define ENABLE_OP_KEY_NUMPAD9               YES

#define ENABLE_OP_KEY_CANCEL                YES
#define ENABLE_OP_KEY_CLEAR                 YES
#define ENABLE_OP_KEY_KANA                  YES
#define ENABLE_OP_KEY_FINAL                 YES
#define ENABLE_OP_KEY_KANJI                 YES
#define ENABLE_OP_KEY_ESCAPE				YES
#define ENABLE_OP_KEY_CONVERT               YES
#define ENABLE_OP_KEY_NONCONVERT            YES
#define ENABLE_OP_KEY_ACCEPT                YES
#define ENABLE_OP_KEY_MODECHANGE            YES
#define ENABLE_OP_KEY_PRINT					YES
#define ENABLE_OP_KEY_EXECUTE               YES
#define ENABLE_OP_KEY_HELP                  YES
#define ENABLE_OP_KEY_WINDOW                YES
#define ENABLE_OP_KEY_SLEEP                 YES

#define ENABLE_OP_KEY_DIVIDE                YES
#define ENABLE_OP_KEY_MULTIPLY              YES
#define ENABLE_OP_KEY_ADD                   YES
#define ENABLE_OP_KEY_SEPARATOR             YES
#define ENABLE_OP_KEY_SUBTRACT              YES
#define ENABLE_OP_KEY_DECIMAL               YES
#define ENABLE_OP_KEY_INSERT                YES
#define ENABLE_OP_KEY_DELETE                YES
#define ENABLE_OP_KEY_BACKSPACE				YES
#define ENABLE_OP_KEY_TAB					YES
#define ENABLE_OP_KEY_SPACE					YES
#define ENABLE_OP_KEY_ENTER					YES
#define ENABLE_OP_KEY_ALT					YES
#define ENABLE_OP_KEY_LEFT_ALT				YES
#define ENABLE_OP_KEY_RIGHT_ALT				YES
#define ENABLE_OP_KEY_SHIFT					YES
#define ENABLE_OP_KEY_LEFT_SHIFT			YES
#define ENABLE_OP_KEY_RIGHT_SHIFT			YES
#define ENABLE_OP_KEY_CTRL					YES
#define ENABLE_OP_KEY_LEFT_CONTROL			YES
#define ENABLE_OP_KEY_RIGHT_CONTROL			YES
#define ENABLE_OP_KEY_META                  YES
#define ENABLE_OP_KEY_CAPS_LOCK				YES
#define ENABLE_OP_KEY_NUM_LOCK				YES
#define ENABLE_OP_KEY_SCROLL_LOCK			YES
#define ENABLE_OP_KEY_PAUSE					YES
#define ENABLE_OP_KEY_PRINTSCREEN			YES
#define ENABLE_OP_KEY_CONTEXT_MENU			YES
#define ENABLE_OP_KEY_NORTH					NO
#define ENABLE_OP_KEY_NORTH_EAST			NO
#define ENABLE_OP_KEY_EAST					NO
#define ENABLE_OP_KEY_SOUTH_EAST			NO
#define ENABLE_OP_KEY_SOUTH					NO
#define ENABLE_OP_KEY_SOUTH_WEST			NO
#define ENABLE_OP_KEY_WEST					NO
#define ENABLE_OP_KEY_NORTH_WEST			NO
#define ENABLE_OP_KEY_OK					NO
#define ENABLE_OP_KEY_RED					NO
#define ENABLE_OP_KEY_GREEN					NO
#define ENABLE_OP_KEY_BLUE					NO
#define ENABLE_OP_KEY_YELLOW				NO
#define ENABLE_OP_KEY_PURPLE				NO
#define ENABLE_OP_KEY_PLAY					NO
#define ENABLE_OP_KEY_PAUSE_RC				NO
#define ENABLE_OP_KEY_STOP					NO
#define ENABLE_OP_KEY_REWIND				NO
#define ENABLE_OP_KEY_FASTFORWARD			NO
#define ENABLE_OP_KEY_RECORD				NO
#define ENABLE_OP_KEY_EXIT					NO
#define ENABLE_OP_KEY_BYPASS				NO
#define ENABLE_OP_KEY_VOLUMEUP				NO
#define ENABLE_OP_KEY_VOLUMEDOWN			NO
#define ENABLE_OP_KEY_CHANNELDOWN			NO
#define ENABLE_OP_KEY_CHANNELUP				NO
#define ENABLE_OP_KEY_FAVOURITE				NO
#define ENABLE_OP_KEY_GUIDE					NO
#define ENABLE_OP_KEY_INFO					NO
#define ENABLE_OP_KEY_LAST_CHANNEL			NO
#define ENABLE_OP_KEY_MUTE					NO
#define ENABLE_OP_KEY_POWER					NO
#define ENABLE_OP_KEY_SETTINGS				NO
#define ENABLE_OP_KEY_MENU					NO
#define ENABLE_OP_KEY_NEXT					NO
#define ENABLE_OP_KEY_PREVIOUS				NO
#define ENABLE_OP_KEY_PAYPERVIEW			NO
#define ENABLE_OP_KEY_MOUSE_BUTTON_1		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_2		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_3		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_4		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_5		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_6		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_7		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_8		YES
#define ENABLE_OP_KEY_MOUSE_BUTTON_9		YES
#define ENABLE_OP_KEY_GESTURE_UP			YES
#define ENABLE_OP_KEY_GESTURE_RIGHT			YES
#define ENABLE_OP_KEY_GESTURE_DOWN			YES
#define ENABLE_OP_KEY_GESTURE_LEFT			YES
#define ENABLE_OP_KEY_GESTURE_UP_LEFT		YES
#define ENABLE_OP_KEY_GESTURE_UP_RIGHT		YES
#define ENABLE_OP_KEY_GESTURE_DOWN_LEFT		YES
#define ENABLE_OP_KEY_GESTURE_DOWN_RIGHT	YES
#define ENABLE_OP_KEY_FLIP_BACK				YES
#define ENABLE_OP_KEY_FLIP_FORWARD			YES
#define ENABLE_OP_KEY_KEYPAD_SIDE			NO
#define ENABLE_OP_KEY_KEYPAD_SOFT1			NO
#define ENABLE_OP_KEY_KEYPAD_SOFT2			NO
#define ENABLE_OP_KEY_KEYPAD_SEND			NO
#define ENABLE_OP_KEY_KEYPAD_END			NO
#define ENABLE_OP_KEY_KEYPAD_BROWSER		NO
#define ENABLE_OP_KEY_KEYPAD_MAIL			NO
#define ENABLE_OP_KEY_KEYPAD_PAGEUP			NO
#define ENABLE_OP_KEY_KEYPAD_PAGEDOWN		NO
#define ENABLE_OP_KEY_KEYPAD_UP				NO
#define ENABLE_OP_KEY_KEYPAD_DOWN			NO
#define ENABLE_OP_KEY_KEYPAD_LEFT			NO
#define ENABLE_OP_KEY_KEYPAD_RIGHT			NO
#define ENABLE_OP_KEY_KEYPAD_OK				NO
#define ENABLE_OP_KEY_KEYPAD_CLEAR			NO
#define ENABLE_OP_KEY_KEYPAD_1				NO
#define ENABLE_OP_KEY_KEYPAD_2				NO
#define ENABLE_OP_KEY_KEYPAD_3				NO
#define ENABLE_OP_KEY_KEYPAD_4				NO
#define ENABLE_OP_KEY_KEYPAD_5				NO
#define ENABLE_OP_KEY_KEYPAD_6				NO
#define ENABLE_OP_KEY_KEYPAD_7				NO
#define ENABLE_OP_KEY_KEYPAD_8				NO
#define ENABLE_OP_KEY_KEYPAD_9				NO
#define ENABLE_OP_KEY_KEYPAD_0				NO
#define ENABLE_OP_KEY_KEYPAD_STAR			NO
#define ENABLE_OP_KEY_KEYPAD_HASH			NO
#define ENABLE_OP_KEY_MAC_CTRL				NO
#define ENABLE_OP_KEY_GP_ANALOG_NORTH		NO
#define ENABLE_OP_KEY_GP_ANALOG_SOUTH		NO
#define ENABLE_OP_KEY_GP_ANALOG_WEST		NO
#define ENABLE_OP_KEY_GP_ANALOG_EAST		NO
#define ENABLE_OP_KEY_GP_DIGITAL_NORTH		NO
#define ENABLE_OP_KEY_GP_DIGITAL_SOUTH		NO
#define ENABLE_OP_KEY_GP_DIGITAL_WEST		NO
#define ENABLE_OP_KEY_GP_DIGITAL_EAST		NO
#define	ENABLE_OP_KEY_GP_A					NO
#define	ENABLE_OP_KEY_GP_B					NO
#define ENABLE_OP_KEY_GP_C_NORTH			NO
#define ENABLE_OP_KEY_GP_C_SOUTH			NO
#define ENABLE_OP_KEY_GP_C_WEST				NO
#define ENABLE_OP_KEY_GP_C_EAST				NO
#define ENABLE_OP_KEY_GP_L					NO
#define ENABLE_OP_KEY_GP_R					NO
#define ENABLE_OP_KEY_GP_X					NO
#define ENABLE_OP_KEY_GP_Y					NO
#define ENABLE_OP_KEY_GP_Z					NO
#define ENABLE_OP_KEY_GP_START				NO

#define ENABLE_OP_KEY_REDO			 	   YES
#define ENABLE_OP_KEY_UNDO			 	   YES
#define ENABLE_OP_KEY_PROPERITES           YES
#define ENABLE_OP_KEY_FRONT	  	  	  	   YES

#define ENABLE_OP_KEY_MAGIC_INPUT_1        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_2        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_3        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_4        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_5        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_6        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_7        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_8        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_9        NO
#define ENABLE_OP_KEY_MAGIC_INPUT_10       NO

# define ENABLE_OP_KEY_SELECT              YES
# define ENABLE_OP_KEY_BACK                NO
# define ENABLE_OP_KEY_CONTEXT1            NO
# define ENABLE_OP_KEY_CONTEXT2            NO
# define ENABLE_OP_KEY_CONTEXT3            NO
# define ENABLE_OP_KEY_CONTEXT4            NO
# define ENABLE_OP_KEY_YES                 NO
# define ENABLE_OP_KEY_NO                  NO
# define ENABLE_OP_KEY_CALL                NO
# define ENABLE_OP_KEY_HANGUP              NO

# define ENABLE_OP_KEY_MAC_CTRL_LEFT       NO
# define ENABLE_OP_KEY_MAC_CTRL_RIGHT      NO
# define ENABLE_OP_KEY_SWIPE_DOWN          NO
# define ENABLE_OP_KEY_SWIPE_LEFT          NO
# define ENABLE_OP_KEY_SWIPE_RIGHT         NO
# define ENABLE_OP_KEY_SWIPE_UP            NO

# define ENABLE_OP_KEY_LEFT_TAB			   YES

#define ENABLE_OP_KEY_XF86XK_MON_BRIGHTNESS_UP		YES
#define ENABLE_OP_KEY_XF86XK_MON_BRIGHTNESS_DOWN	YES
#define ENABLE_OP_KEY_XF86XK_KBD_LIGHT_ON_OFF		YES
#define ENABLE_OP_KEY_XF86XK_KBD_BRIGHTNESS_UP		YES
#define ENABLE_OP_KEY_XF86XK_KBD_BRIGHTNESS_DOWN	YES

#define ENABLE_OP_KEY_XF86XK_STANDBY				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_LOWER_VOLUME		YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_MUTE				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_RAISE_VOLUME		YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_PLAY				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_STOP				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_PREV				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_NEXT				YES
#define ENABLE_OP_KEY_XF86XK_HOME_PAGE				YES
#define ENABLE_OP_KEY_XF86XK_MAIL					YES
#define ENABLE_OP_KEY_XF86XK_START					YES
#define ENABLE_OP_KEY_XF86XK_SEARCH					YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_RECORD			YES

#define ENABLE_OP_KEY_XF86XK_CALCULATOR				YES
#define ENABLE_OP_KEY_XF86XK_MEMO					YES
#define ENABLE_OP_KEY_XF86XK_TO_DO_LIST				YES
#define ENABLE_OP_KEY_XF86XK_CALENDAR				YES
#define ENABLE_OP_KEY_XF86XK_POWER_DOWN				YES
#define ENABLE_OP_KEY_XF86XK_CONTRAST_ADJUST		YES
#define ENABLE_OP_KEY_XF86XK_ROCKER_UP				YES
#define ENABLE_OP_KEY_XF86XK_ROCKER_DOWN			YES
#define ENABLE_OP_KEY_XF86XK_ROCKER_ENTER			YES

#define ENABLE_OP_KEY_XF86XK_BACK					YES
#define ENABLE_OP_KEY_XF86XK_FORWARD				YES
#define ENABLE_OP_KEY_XF86XK_STOP					YES
#define ENABLE_OP_KEY_XF86XK_REFRESH				YES
#define ENABLE_OP_KEY_XF86XK_POWER_OFF				YES
#define ENABLE_OP_KEY_XF86XK_WAKE_UP				YES
#define ENABLE_OP_KEY_XF86XK_EJECT					YES
#define ENABLE_OP_KEY_XF86XK_SCREEN_SAVER			YES
#define ENABLE_OP_KEY_XF86XK_WWW					YES
#define ENABLE_OP_KEY_XF86XK_FAVORITES				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_PAUSE			YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_MEDIA			YES
#define ENABLE_OP_KEY_XF86XK_MY_COMPUTER			YES
#define ENABLE_OP_KEY_XF86XK_VENDOR_HOME			YES
#define ENABLE_OP_KEY_XF86XK_LIGHT_BULB				YES
#define ENABLE_OP_KEY_XF86XK_SHOP					YES
#define ENABLE_OP_KEY_XF86XK_HISTORY				YES
#define ENABLE_OP_KEY_XF86XK_OPEN_URL				YES
#define ENABLE_OP_KEY_XF86XK_ADD_FAVORITE			YES
#define ENABLE_OP_KEY_XF86XK_HOT_LINKS				YES
#define ENABLE_OP_KEY_XF86XK_BRIGHTNESS_ADJUST		YES
#define ENABLE_OP_KEY_XF86XK_FINANCE				YES
#define ENABLE_OP_KEY_XF86XK_COMMUNITY				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_REWIND			YES
#define ENABLE_OP_KEY_XF86XK_BACK_FORWARD			YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH0				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH1				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH2				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH3				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH4				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH5				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH6				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH7				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH8				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH9				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH_A				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH_B				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH_C				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH_D				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH_E				YES
#define ENABLE_OP_KEY_XF86XK_LAUNCH_F				YES

#define ENABLE_OP_KEY_XF86XK_APPLICATION_LEFT		YES
#define ENABLE_OP_KEY_XF86XK_APPLICATION_RIGHT		YES
#define ENABLE_OP_KEY_XF86XK_BOOK					YES
#define ENABLE_OP_KEY_XF86XK_CD						YES
#define ENABLE_OP_KEY_XF86XK_CLOSE					YES
#define ENABLE_OP_KEY_XF86XK_COPY					YES
#define ENABLE_OP_KEY_XF86XK_CUT					YES
#define ENABLE_OP_KEY_XF86XK_DISPLAY				YES
#define ENABLE_OP_KEY_XF86XK_DOS					YES
#define ENABLE_OP_KEY_XF86XK_DOCUMENTS				YES
#define ENABLE_OP_KEY_XF86XK_EXCEL					YES
#define ENABLE_OP_KEY_XF86XK_EXPLORER				YES
#define ENABLE_OP_KEY_XF86XK_GAME					YES
#define ENABLE_OP_KEY_XF86XK_GO						YES
#define ENABLE_OP_KEY_XF86XK_I_TOUCH				YES
#define ENABLE_OP_KEY_XF86XK_LOG_OFF				YES
#define ENABLE_OP_KEY_XF86XK_MARKET					YES
#define ENABLE_OP_KEY_XF86XK_MEETING				YES
#define ENABLE_OP_KEY_XF86XK_MENU_KB				YES
#define ENABLE_OP_KEY_XF86XK_MENU_PB				YES
#define ENABLE_OP_KEY_XF86XK_MY_SITES				YES
#define ENABLE_OP_KEY_XF86XK_NEW					YES
#define ENABLE_OP_KEY_XF86XK_NEWS					YES
#define ENABLE_OP_KEY_XF86XK_OFFICE_HOME			YES
#define ENABLE_OP_KEY_XF86XK_OPEN					YES
#define ENABLE_OP_KEY_XF86XK_OPTION					YES
#define ENABLE_OP_KEY_XF86XK_PASTE					YES
#define ENABLE_OP_KEY_XF86XK_PHONE					YES
#define ENABLE_OP_KEY_XF86XK_REPLY					YES
#define ENABLE_OP_KEY_XF86XK_RELOAD					YES
#define ENABLE_OP_KEY_XF86XK_ROTATE_WINDOWS			YES
#define ENABLE_OP_KEY_XF86XK_ROTATION_PB			YES
#define ENABLE_OP_KEY_XF86XK_ROTATION_KB			YES
#define ENABLE_OP_KEY_XF86XK_SAVE					YES
#define ENABLE_OP_KEY_XF86XK_SCROLL_UP				YES
#define ENABLE_OP_KEY_XF86XK_SCROLL_DOWN			YES
#define ENABLE_OP_KEY_XF86XK_SCROLL_CLICK			YES
#define ENABLE_OP_KEY_XF86XK_SEND					YES
#define ENABLE_OP_KEY_XF86XK_SPELL					YES
#define ENABLE_OP_KEY_XF86XK_SPLIT_SCREEN			YES
#define ENABLE_OP_KEY_XF86XK_SUPPORT				YES
#define ENABLE_OP_KEY_XF86XK_TASK_PANE				YES
#define ENABLE_OP_KEY_XF86XK_TERMINAL				YES
#define ENABLE_OP_KEY_XF86XK_TOOLS					YES
#define ENABLE_OP_KEY_XF86XK_TRAVEL					YES
#define ENABLE_OP_KEY_XF86XK_USER_PB				YES
#define ENABLE_OP_KEY_XF86XK_USER1KB				YES
#define ENABLE_OP_KEY_XF86XK_USER2KB				YES
#define ENABLE_OP_KEY_XF86XK_VIDEO					YES
#define ENABLE_OP_KEY_XF86XK_WHEEL_BUTTON			YES
#define ENABLE_OP_KEY_XF86XK_WORD					YES
#define ENABLE_OP_KEY_XF86XK_XFER					YES
#define ENABLE_OP_KEY_XF86XK_ZOOM_IN				YES
#define ENABLE_OP_KEY_XF86XK_ZOOM_OUT				YES

#define ENABLE_OP_KEY_XF86XK_AWAY					YES
#define ENABLE_OP_KEY_XF86XK_MESSENGER				YES
#define ENABLE_OP_KEY_XF86XK_WEB_CAM				YES
#define ENABLE_OP_KEY_XF86XK_MAIL_FORWARD			YES
#define ENABLE_OP_KEY_XF86XK_PICTURES				YES
#define ENABLE_OP_KEY_XF86XK_MUSIC					YES

#define ENABLE_OP_KEY_XF86XK_BATTERY				YES
#define ENABLE_OP_KEY_XF86XK_BLUETOOTH				YES
#define ENABLE_OP_KEY_XF86XK_WLAN					YES
#define ENABLE_OP_KEY_XF86XK_UWB					YES

#define ENABLE_OP_KEY_XF86XK_AUDIO_FORWARD			YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_REPEAT			YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_RANDOM_PLAY		YES
#define ENABLE_OP_KEY_XF86XK_SUBTITLE				YES
#define ENABLE_OP_KEY_XF86XK_AUDIO_CYCLE_TRACK		YES
#define ENABLE_OP_KEY_XF86XK_CYCLE_ANGLE			YES
#define ENABLE_OP_KEY_XF86XK_FRAME_BACK				YES
#define ENABLE_OP_KEY_XF86XK_FRAME_FORWARD			YES
#define ENABLE_OP_KEY_XF86XK_TIME					YES
#define ENABLE_OP_KEY_XF86XK_VIEW					YES
#define ENABLE_OP_KEY_XF86XK_TOP_MENU				YES

#define ENABLE_OP_KEY_XF86XK_RED					YES
#define ENABLE_OP_KEY_XF86XK_GREEN					YES
#define ENABLE_OP_KEY_XF86XK_YELLOW					YES
#define ENABLE_OP_KEY_XF86XK_BLUE					YES

#define ENABLE_OP_KEY_XF86XK_SUSPEND				YES
#define ENABLE_OP_KEY_XF86XK_HIBERNATE				YES


#define ENABLE_OP_KEY_HK_TOGGLE						YES
#define ENABLE_OP_KEY_KATAKANA						YES
#define ENABLE_OP_KEY_HIRAGANA						YES
