// <copyright header>

// Please don't modify this file.

// This file is automatically generated by opera.pike

#ifndef MODULES_HARDCORE_BASE_CAPABILITIES_H
#define MODULES_HARDCORE_BASE_CAPABILITIES_H

// <capabilities>

#endif // !MODULES_HARDCORE_BASE_CAPABILITIES_H
