// <copyright header>

// <autogenerated system.pike>

// You need to define PRODUCT_SYSTEM_FILE to be the path to the file where
// you set your system's configuration. Define each system setting to either YES or NO.

#ifndef MODULES_HARDCORE_BASE_SYSTEM_H
#define MODULES_HARDCORE_BASE_SYSTEM_H

// Make sure YES and NO are set.

#define YES 1
#define NO 0

#ifndef PRODUCT_SYSTEM_FILE
#error "PRODUCT_SYSTEM_FILE not defined."
#endif // !PRODUCT_SYSTEM_FILE

#include PRODUCT_SYSTEM_FILE

// Deprecated or redesigned system settings goes here.

// <deprecated systems>

// Make sure all system settings have been determined.

// <system choice check>

// Check dependencies.

// <system dependency check>

// Turn on defines.

// <system defines>

// Check types.

// <check system types>

// Check macros.

// <check macros>

#ifndef HAVE_OP_YIELD
#define op_yield() ((void)(0))
#endif // HAVE_YIELD

// Undefine YES and NO.

#undef YES
#undef NO

// Undefine all SYSTEM_ defines.

// <system undefines>

#endif // !MODULES_HARDCORE_BASE_SYSTEM_H
