// <copyright header>

// <autogenerated tweaks_and_api.py>

#ifndef MODULES_HARDCORE_BASE_TWEAKS_AND_APIS_H
#define MODULES_HARDCORE_BASE_TWEAKS_AND_APIS_H

#ifndef PRODUCT_TWEAKS_FILE
#error "PRODUCT_TWEAKS_FILE not defined."
#endif // !PRODUCT_TWEAKS_FILE

#include PRODUCT_TWEAKS_FILE

#include "local-tweaks.h"

// <main clause>

// <conflicts with clause>

// <undefine clause>

#endif // !MODULES_HARDCORE_BASE_TWEAKS_AND_APIS_H
